/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const DevOrgAuthConnectionsDeleteRequest: core.serialization.Schema<serializers.DevOrgAuthConnectionsDeleteRequest.Raw, DevrevApi.DevOrgAuthConnectionsDeleteRequest>;
export declare namespace DevOrgAuthConnectionsDeleteRequest {
    interface Raw {
        id: string;
    }
}
