/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AuthTokensCreateRequest: core.serialization.Schema<serializers.AuthTokensCreateRequest.Raw, DevrevApi.AuthTokensCreateRequest>;
export declare namespace AuthTokensCreateRequest {
    interface Raw {
        act_as?: string | null;
        aud?: string[] | null;
        client_id?: string | null;
        expires_in?: number | null;
        grant_type?: serializers.AuthTokenGrantType.Raw | null;
        requested_token_type?: serializers.AuthTokenRequestedTokenType.Raw | null;
        rev_info?: serializers.AuthTokensRevInfo.Raw | null;
        scope?: string | null;
        subject_token?: string | null;
        subject_token_type?: serializers.AuthTokenSubjectTokenType.Raw | null;
        token_hint?: string | null;
    }
}
