/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AuthTokensSelfDeleteRequest: core.serialization.Schema<serializers.AuthTokensSelfDeleteRequest.Raw, DevrevApi.AuthTokensSelfDeleteRequest>;
export declare namespace AuthTokensSelfDeleteRequest {
    interface Raw {
        requested_token_type?: serializers.AuthTokenRequestedTokenType.Raw | null;
    }
}
