/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AuthTokensListRequest: core.serialization.Schema<serializers.AuthTokensListRequest.Raw, DevrevApi.AuthTokensListRequest>;
export declare namespace AuthTokensListRequest {
    interface Raw {
        client_id?: string | null;
        requested_token_type?: serializers.AuthTokenRequestedTokenType.Raw | null;
        subject?: string | null;
    }
}
