/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AuthTokensUpdateRequest: core.serialization.Schema<serializers.AuthTokensUpdateRequest.Raw, DevrevApi.AuthTokensUpdateRequest>;
export declare namespace AuthTokensUpdateRequest {
    interface Raw {
        token_hint: string;
        token_id: string;
    }
}
