/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const ArtifactsGetRequest: core.serialization.Schema<serializers.ArtifactsGetRequest.Raw, DevrevApi.ArtifactsGetRequest>;
export declare namespace ArtifactsGetRequest {
    interface Raw {
        id: string;
        version?: string | null;
    }
}
