/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const ArtifactsLocateRequest: core.serialization.Schema<serializers.ArtifactsLocateRequest.Raw, DevrevApi.ArtifactsLocateRequest>;
export declare namespace ArtifactsLocateRequest {
    interface Raw {
        id: string;
        version?: string | null;
    }
}
