/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const ArtifactsListRequest: core.serialization.Schema<serializers.ArtifactsListRequest.Raw, DevrevApi.ArtifactsListRequest>;
export declare namespace ArtifactsListRequest {
    interface Raw {
        parent_id?: string | null;
    }
}
