/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const TagsUpdateRequest: core.serialization.Schema<serializers.TagsUpdateRequest.Raw, DevrevApi.TagsUpdateRequest>;
export declare namespace TagsUpdateRequest {
    interface Raw {
        allowed_values?: serializers.TagsUpdateAllowedValues.Raw | null;
        description?: string | null;
        id: string;
        name?: string | null;
    }
}
