/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const TagsListRequest: core.serialization.Schema<serializers.TagsListRequest.Raw, DevrevApi.TagsListRequest>;
export declare namespace TagsListRequest {
    interface Raw {
        cursor?: string | null;
        limit?: number | null;
        mode?: serializers.ListMode.Raw | null;
        name?: string[] | null;
        sort_by?: string[] | null;
    }
}
