/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const TagsGetRequest: core.serialization.Schema<serializers.TagsGetRequest.Raw, DevrevApi.TagsGetRequest>;
export declare namespace TagsGetRequest {
    interface Raw {
        id: string;
    }
}
