/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "../../../..";
/**
 * @example
 *     {}
 */
export interface WorksExportRequest {
    actualCloseDate?: DevrevApi.DateFilter;
    /** Filters for work belonging to any of the provided parts. */
    appliesToPart?: string[];
    /** Filters for work created by any of these users. */
    createdBy?: string[];
    createdDate?: DevrevApi.DateFilter;
    /**
     * The number of work items to return. The default is '50', the
     * maximum is '5000'.
     *
     */
    first?: number;
    issue?: DevrevApi.WorksFilterIssue;
    modifiedDate?: DevrevApi.DateFilter;
    /** Filters for work owned by any of these users. */
    ownedBy?: string[];
    /** Filters for work reported by any of these users. */
    reportedBy?: string[];
    stage?: DevrevApi.StageFilter;
    stagedInfo?: DevrevApi.StagedInfoFilter;
    syncMetadata?: DevrevApi.SyncMetadataFilter;
    /** Filters for work with any of the provided tags. */
    tags?: string[];
    targetCloseDate?: DevrevApi.DateFilter;
    ticket?: DevrevApi.WorksFilterTicket;
    /** Filters for work of the provided types. */
    type?: DevrevApi.WorkType[];
}
