/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "../../../..";
/**
 * @example
 *     {}
 */
export interface WorksListQuery {
    /**
     * Filters for work belonging to any of the provided parts.
     */
    appliesToPart?: string | string[];
    /**
     * Filters for work created by any of these users.
     */
    createdBy?: string | string[];
    /**
     * The cursor to resume iteration from. If not provided, then iteration
     * starts from the beginning.
     */
    cursor?: string;
    /**
     * Filters for issues with any of the provided Accounts.
     */
    issueAccounts?: string | string[];
    /**
     * Filters for issues with any of the provided priorities.
     */
    issuePriority?: DevrevApi.IssuePriority | DevrevApi.IssuePriority[];
    /**
     * Filters for issues with any of the provided priority enum ids.
     */
    issuePriorityV2?: number | number[];
    /**
     * Filters for issues with any of the provided Rev organizations.
     */
    issueRevOrgs?: string | string[];
    /**
     * The maximum number of works to return. The default is '50'.
     */
    limit?: number;
    /**
     * The iteration mode to use, otherwise if not set, then "after" is
     * used.
     */
    mode?: DevrevApi.ListMode;
    /**
     * Filters for work owned by any of these users.
     */
    ownedBy?: string | string[];
    /**
     * Filters for work reported by any of these users.
     */
    reportedBy?: string | string[];
    /**
     * Filters for records in the provided stage(s) by name.
     */
    stageName?: string | string[];
    /**
     * Filters for issues that are staged.
     */
    stagedInfoIsStaged?: boolean;
    /**
     * Filters for works with selected sync statuses.
     */
    syncMetadataLastSyncInStatus?: DevrevApi.SyncMetadataFilterSyncInFilterStatus | DevrevApi.SyncMetadataFilterSyncInFilterStatus[];
    /**
     * Filters for works modified with selected sync units.
     */
    syncMetadataLastSyncInSyncUnit?: string | string[];
    /**
     * Filters for works with selected sync statuses.
     */
    syncMetadataLastSyncOutStatus?: DevrevApi.SyncMetadataFilterSyncOutFilterStatus | DevrevApi.SyncMetadataFilterSyncOutFilterStatus[];
    /**
     * Filters for works modified with selected sync units.
     */
    syncMetadataLastSyncOutSyncUnit?: string | string[];
    /**
     * Filters for issues synced from this specific origin system.
     */
    syncMetadataOriginSystem?: string | string[];
    /**
     * Filters for work with any of the provided tags.
     */
    tags?: string | string[];
    /**
     * Filters for tickets with any of the provided channels.
     */
    ticketChannels?: DevrevApi.TicketChannels | DevrevApi.TicketChannels[];
    /**
     * Filters for tickets belonging to specific groups.
     */
    ticketGroup?: string | string[];
    /**
     * Filters for tickets that are spam.
     */
    ticketIsSpam?: boolean;
    /**
     * Filters for tickets that need response.
     */
    ticketNeedsResponse?: boolean;
    /**
     * Filters for tickets that are associated with any of the provided Rev
     * organizations.
     */
    ticketRevOrg?: string | string[];
    /**
     * Filters for tickets with any of the provided severities.
     */
    ticketSeverity?: DevrevApi.TicketSeverity | DevrevApi.TicketSeverity[];
    /**
     * Filters for records with any of the provided SLA stages.
     */
    ticketSlaSummaryStage?: DevrevApi.SlaSummaryStage | DevrevApi.SlaSummaryStage[];
    /**
     * Filters for tickets with any of the provided source channels.
     */
    ticketSourceChannel?: string | string[];
    /**
     * Filters for work of the provided types.
     */
    type?: DevrevApi.WorkType | DevrevApi.WorkType[];
}
