/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         id: "TAG-12345"
 *     }
 */
export interface TagsGetQuery {
    /**
     * The requested tag's ID.
     */
    id: string;
}
