/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "../../../..";
/**
 * @example
 *     {}
 */
export interface TagsListQuery {
    /**
     * The cursor to resume iteration from. If not provided, then iteration
     * starts from the beginning.
     */
    cursor?: string;
    /**
     * The maximum number of tags to return. The default is '50'.
     */
    limit?: number;
    /**
     * The iteration mode to use, otherwise if not set, then "after" is
     * used.
     */
    mode?: DevrevApi.ListMode;
    /**
     * Filters for tags with the provided names.
     */
    name?: string | string[];
    /**
     * Fields to sort tags by and the direction to sort them.
     */
    sortBy?: string | string[];
}
