/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "../../../..";
/**
 * @example
 *     {}
 */
export interface AuthTokensListQuery {
    /**
     * An identifier that represents the application, which requested the
     * token. Only relevant for application access tokens.
     */
    clientId?: string;
    /**
     * The type of the requested token. If no value is specified, the
     * response will include tokens of all the types.
     */
    requestedTokenType?: DevrevApi.AuthTokenRequestedTokenType;
    /**
     * The subject associated with the token. In the absence of this
     * parameter, the ID of the authenticated entity is treated as the
     * subject.
     */
    subject?: string;
}
