"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DevrevApiClient = void 0;
const Client_1 = require("./api/resources/accounts/client/Client");
const Client_2 = require("./api/resources/artifacts/client/Client");
const Client_3 = require("./api/resources/authTokens/client/Client");
const Client_4 = require("./api/resources/authConnection/client/Client");
const Client_5 = require("./api/resources/devUsers/client/Client");
const Client_6 = require("./api/resources/parts/client/Client");
const Client_7 = require("./api/resources/revOrgs/client/Client");
const Client_8 = require("./api/resources/slas/client/Client");
const Client_9 = require("./api/resources/tags/client/Client");
const Client_10 = require("./api/resources/timelineEntries/client/Client");
const Client_11 = require("./api/resources/webhooks/client/Client");
const Client_12 = require("./api/resources/works/client/Client");
class DevrevApiClient {
    constructor(_options) {
        this._options = _options;
    }
    get accounts() {
        var _a;
        return ((_a = this._accounts) !== null && _a !== void 0 ? _a : (this._accounts = new Client_1.Accounts(this._options)));
    }
    get artifacts() {
        var _a;
        return ((_a = this._artifacts) !== null && _a !== void 0 ? _a : (this._artifacts = new Client_2.Artifacts(this._options)));
    }
    get authTokens() {
        var _a;
        return ((_a = this._authTokens) !== null && _a !== void 0 ? _a : (this._authTokens = new Client_3.AuthTokens(this._options)));
    }
    get authConnection() {
        var _a;
        return ((_a = this._authConnection) !== null && _a !== void 0 ? _a : (this._authConnection = new Client_4.AuthConnection(this._options)));
    }
    get devUsers() {
        var _a;
        return ((_a = this._devUsers) !== null && _a !== void 0 ? _a : (this._devUsers = new Client_5.DevUsers(this._options)));
    }
    get parts() {
        var _a;
        return ((_a = this._parts) !== null && _a !== void 0 ? _a : (this._parts = new Client_6.Parts(this._options)));
    }
    get revOrgs() {
        var _a;
        return ((_a = this._revOrgs) !== null && _a !== void 0 ? _a : (this._revOrgs = new Client_7.RevOrgs(this._options)));
    }
    get slas() {
        var _a;
        return ((_a = this._slas) !== null && _a !== void 0 ? _a : (this._slas = new Client_8.Slas(this._options)));
    }
    get tags() {
        var _a;
        return ((_a = this._tags) !== null && _a !== void 0 ? _a : (this._tags = new Client_9.Tags(this._options)));
    }
    get timelineEntries() {
        var _a;
        return ((_a = this._timelineEntries) !== null && _a !== void 0 ? _a : (this._timelineEntries = new Client_10.TimelineEntries(this._options)));
    }
    get webhooks() {
        var _a;
        return ((_a = this._webhooks) !== null && _a !== void 0 ? _a : (this._webhooks = new Client_11.Webhooks(this._options)));
    }
    get works() {
        var _a;
        return ((_a = this._works) !== null && _a !== void 0 ? _a : (this._works = new Client_12.Works(this._options)));
    }
}
exports.DevrevApiClient = DevrevApiClient;
