/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Accounts } from "./api/resources/accounts/client/Client";
import { Artifacts } from "./api/resources/artifacts/client/Client";
import { AuthTokens } from "./api/resources/authTokens/client/Client";
import { AuthConnection } from "./api/resources/authConnection/client/Client";
import { DevUsers } from "./api/resources/devUsers/client/Client";
import { Parts } from "./api/resources/parts/client/Client";
import { RevOrgs } from "./api/resources/revOrgs/client/Client";
import { Slas } from "./api/resources/slas/client/Client";
import { Tags } from "./api/resources/tags/client/Client";
import { TimelineEntries } from "./api/resources/timelineEntries/client/Client";
import { Webhooks } from "./api/resources/webhooks/client/Client";
import { Works } from "./api/resources/works/client/Client";
export declare namespace DevrevApiClient {
    interface Options {
        environment?: core.Supplier<environments.DevrevApiEnvironment | string>;
        apiKey: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class DevrevApiClient {
    protected readonly _options: DevrevApiClient.Options;
    constructor(_options: DevrevApiClient.Options);
    protected _accounts: Accounts | undefined;
    get accounts(): Accounts;
    protected _artifacts: Artifacts | undefined;
    get artifacts(): Artifacts;
    protected _authTokens: AuthTokens | undefined;
    get authTokens(): AuthTokens;
    protected _authConnection: AuthConnection | undefined;
    get authConnection(): AuthConnection;
    protected _devUsers: DevUsers | undefined;
    get devUsers(): DevUsers;
    protected _parts: Parts | undefined;
    get parts(): Parts;
    protected _revOrgs: RevOrgs | undefined;
    get revOrgs(): RevOrgs;
    protected _slas: Slas | undefined;
    get slas(): Slas;
    protected _tags: Tags | undefined;
    get tags(): Tags;
    protected _timelineEntries: TimelineEntries | undefined;
    get timelineEntries(): TimelineEntries;
    protected _webhooks: Webhooks | undefined;
    get webhooks(): Webhooks;
    protected _works: Works | undefined;
    get works(): Works;
}
