/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const DevrevApiEnvironment: {
    readonly Default: "https://api.devrev.ai";
};
export declare type DevrevApiEnvironment = typeof DevrevApiEnvironment.Default;
