/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {}
 */
export interface ArtifactsListQuery {
    /**
     * The ID of the object to filter artifacts.
     */
    parentId?: string;
}
