/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const PartsDeleteRequest: core.serialization.Schema<serializers.PartsDeleteRequest.Raw, DevrevApi.PartsDeleteRequest>;
export declare namespace PartsDeleteRequest {
    interface Raw {
        id: string;
    }
}
