/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "../../../..";
/**
 * @example
 *     {
 *         createdDateAfter: new Date("2023-01-01T12:00:00.000Z"),
 *         createdDateBefore: new Date("2023-01-01T12:00:00.000Z"),
 *         modifiedDateAfter: new Date("2023-01-01T12:00:00.000Z"),
 *         modifiedDateBefore: new Date("2023-01-01T12:00:00.000Z")
 *     }
 */
export interface AccountsListQuery {
    /**
     * Filters for accounts created by the specified user(s).
     */
    createdBy?: string | string[];
    /**
     * Filters for objects created after the provided timestamp (inclusive).
     */
    createdDateAfter?: Date;
    /**
     * Filters for objects created before the provided timestamp
     * (inclusive).
     */
    createdDateBefore?: Date;
    /**
     * The cursor to resume iteration from. If not provided, then iteration
     * starts from the beginning.
     */
    cursor?: string;
    /**
     * Array of display names of accounts to be filtered.
     */
    displayName?: string | string[];
    /**
     * Array of references of accounts to be filtered.
     */
    externalRefs?: string | string[];
    /**
     * The maximum number of accounts to return per page. The default is
     * '50'.
     */
    limit?: number;
    /**
     * The iteration mode to use, otherwise if not set, then "after" is
     * used.
     */
    mode?: DevrevApi.ListMode;
    /**
     * Filters for objects created after the provided timestamp (inclusive).
     */
    modifiedDateAfter?: Date;
    /**
     * Filters for objects created before the provided timestamp
     * (inclusive).
     */
    modifiedDateBefore?: Date;
    /**
     * Fields to sort the accounts by and the direction to sort them in.
     */
    sortBy?: string | string[];
    /**
     * Filters for accounts on specified stages.
     */
    stage?: string | string[];
}
