/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "../../../..";
/**
 * @example
 *     {}
 */
export interface AccountsListRequest {
    /** Filters for accounts created by the specified user(s). */
    createdBy?: string[];
    createdDate?: DevrevApi.DateTimeFilter;
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /** Array of display names of accounts to be filtered. */
    displayName?: string[];
    /** Array of references of accounts to be filtered. */
    externalRefs?: string[];
    /**
     * The maximum number of accounts to return per page. The default is
     * '50'.
     *
     */
    limit?: number;
    mode?: DevrevApi.ListMode;
    modifiedDate?: DevrevApi.DateTimeFilter;
    /**
     * Fields to sort the accounts by and the direction to sort them in.
     *
     */
    sortBy?: string[];
    /** Filters for accounts on specified stages. */
    stage?: string[];
}
