paths:
  /articles.create:
    post:
      x-fern-sdk-group-name:
        - articles
      x-fern-sdk-method-name: create
  /articles.delete:
    post:
      x-fern-sdk-group-name:
        - articles
      x-fern-sdk-method-name: delete
  /articles.get:
    get:
      x-fern-sdk-group-name:
        - articles
      x-fern-sdk-method-name: get
    post:
      x-fern-sdk-group-name:
        - articles
      x-fern-sdk-method-name: get-post
  /articles.list:
    get:
      x-fern-sdk-group-name:
        - articles
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - articles
      x-fern-sdk-method-name: list-post
  /articles.update:
    post:
      x-fern-sdk-group-name:
        - articles
      x-fern-sdk-method-name: update
  /event-sources.get:
    get:
      x-fern-sdk-group-name:
        - eventSource
      x-fern-sdk-method-name: get
    post:
      x-fern-sdk-group-name:
        - eventSource
      x-fern-sdk-method-name: get-post
  /event-sources.schedule:
    post:
      x-fern-sdk-group-name:
        - eventSource
      x-fern-sdk-method-name: schedule-event
  /event-sources.unschedule:
    post:
      x-fern-sdk-group-name:
        - eventSource
      x-fern-sdk-method-name: delete-scheduled-event
  /fragments.create:
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: fragments-create
  /fragments.get:
    get:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: fragments-get
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: fragments-get-post
  /fragments.transition:
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: fragments-transition
  /org-schedules.create:
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: create
  /org-schedules.get:
    get:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: get
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: get-post
  /org-schedules.list:
    get:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: list-post
  /org-schedules.set-future:
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: set-future
  /org-schedules.transition:
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: transition
  /org-schedules.update:
    post:
      x-fern-sdk-group-name:
        - schedules
      x-fern-sdk-method-name: update
  /question-answers.create:
    post:
      x-fern-sdk-group-name:
        - questionAnswers
      x-fern-sdk-method-name: create
  /question-answers.delete:
    post:
      x-fern-sdk-group-name:
        - questionAnswers
      x-fern-sdk-method-name: delete
  /question-answers.get:
    get:
      x-fern-sdk-group-name:
        - questionAnswers
      x-fern-sdk-method-name: get
    post:
      x-fern-sdk-group-name:
        - questionAnswers
      x-fern-sdk-method-name: get-post
  /question-answers.list:
    get:
      x-fern-sdk-group-name:
        - questionAnswers
      x-fern-sdk-method-name: list
    post:
      x-fern-sdk-group-name:
        - questionAnswers
      x-fern-sdk-method-name: list-post
  /question-answers.update:
    post:
      x-fern-sdk-group-name:
        - questionAnswers
      x-fern-sdk-method-name: update
components:
  securitySchemes:
    auth-token:
      type: http
      scheme: bearer
      x-fern-bearer:
        name: token
        env: DEVREV_TOKEN
  