/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const WebhooksCreateRequest: core.serialization.Schema<serializers.WebhooksCreateRequest.Raw, DevrevApi.WebhooksCreateRequest>;
export declare namespace WebhooksCreateRequest {
    interface Raw {
        event_types?: serializers.WebhookEventType.Raw[] | null;
        secret?: string | null;
        url: string;
    }
}
