/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const WebhooksUpdateRequest: core.serialization.Schema<serializers.WebhooksUpdateRequest.Raw, DevrevApi.WebhooksUpdateRequest>;
export declare namespace WebhooksUpdateRequest {
    interface Raw {
        action?: serializers.WebhooksUpdateAction.Raw | null;
        event_types?: serializers.WebhooksUpdateRequestEventTypes.Raw | null;
        id: string;
        secret?: string | null;
        url?: string | null;
    }
}
