/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const WebhooksGetRequest: core.serialization.Schema<serializers.WebhooksGetRequest.Raw, DevrevApi.WebhooksGetRequest>;
export declare namespace WebhooksGetRequest {
    interface Raw {
        id: string;
    }
}
