/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const WebhooksDeleteRequest: core.serialization.Schema<serializers.WebhooksDeleteRequest.Raw, DevrevApi.WebhooksDeleteRequest>;
export declare namespace WebhooksDeleteRequest {
    interface Raw {
        id: string;
    }
}
