/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors";
import * as DevrevApi from "..";
export declare class ForbiddenError extends errors.DevrevApiError {
    constructor(body: DevrevApi.ErrorForbidden);
}
