/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface DevOrgAuthConnectionsGetQuery {
    /**
     * ID of the authentication connection.
     */
    id: string;
}
