/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const TimelineEntriesGetRequest: core.serialization.Schema<serializers.TimelineEntriesGetRequest.Raw, DevrevApi.TimelineEntriesGetRequest>;
export declare namespace TimelineEntriesGetRequest {
    interface Raw {
        id: string;
    }
}
