/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const WorksDeleteRequest: core.serialization.Schema<serializers.WorksDeleteRequest.Raw, DevrevApi.WorksDeleteRequest>;
export declare namespace WorksDeleteRequest {
    interface Raw {
        id: string;
    }
}
