/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const WorksExportRequest: core.serialization.Schema<serializers.WorksExportRequest.Raw, DevrevApi.WorksExportRequest>;
export declare namespace WorksExportRequest {
    interface Raw {
        actual_close_date?: serializers.DateFilter.Raw | null;
        applies_to_part?: string[] | null;
        created_by?: string[] | null;
        created_date?: serializers.DateFilter.Raw | null;
        first?: number | null;
        issue?: serializers.WorksFilterIssue.Raw | null;
        modified_date?: serializers.DateFilter.Raw | null;
        owned_by?: string[] | null;
        reported_by?: string[] | null;
        stage?: serializers.StageFilter.Raw | null;
        staged_info?: serializers.StagedInfoFilter.Raw | null;
        sync_metadata?: serializers.SyncMetadataFilter.Raw | null;
        tags?: string[] | null;
        target_close_date?: serializers.DateFilter.Raw | null;
        ticket?: serializers.WorksFilterTicket.Raw | null;
        type?: serializers.WorkType.Raw[] | null;
    }
}
