/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Account: core.serialization.ObjectSchema<serializers.Account.Raw, DevrevApi.Account>;
export declare namespace Account {
    interface Raw extends serializers.OrgBase.Raw {
        description?: string | null;
        domains?: string[] | null;
        external_refs: string[];
        owned_by: serializers.UserSummary.Raw[];
        tier?: string | null;
    }
}
