/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AccountsCreateResponse: core.serialization.ObjectSchema<serializers.AccountsCreateResponse.Raw, DevrevApi.AccountsCreateResponse>;
export declare namespace AccountsCreateResponse {
    interface Raw {
        account: serializers.Account.Raw;
    }
}
