/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AccountsExportResponse: core.serialization.ObjectSchema<serializers.AccountsExportResponse.Raw, DevrevApi.AccountsExportResponse>;
export declare namespace AccountsExportResponse {
    interface Raw {
        accounts: serializers.Account.Raw[];
    }
}
