/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AccountsListResponse: core.serialization.ObjectSchema<serializers.AccountsListResponse.Raw, DevrevApi.AccountsListResponse>;
export declare namespace AccountsListResponse {
    interface Raw {
        accounts: serializers.Account.Raw[];
        next_cursor?: string | null;
        prev_cursor?: string | null;
    }
}
