/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ArtifactsPrepareResponseFormData: core.serialization.ObjectSchema<serializers.ArtifactsPrepareResponseFormData.Raw, DevrevApi.ArtifactsPrepareResponseFormData>;
export declare namespace ArtifactsPrepareResponseFormData {
    interface Raw {
        key: string;
        value: string;
    }
}
