/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ArtifactsLocateResponse: core.serialization.ObjectSchema<serializers.ArtifactsLocateResponse.Raw, DevrevApi.ArtifactsLocateResponse>;
export declare namespace ArtifactsLocateResponse {
    interface Raw {
        expires_at?: string | null;
        url: string;
    }
}
