/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ArtifactsGetResponse: core.serialization.ObjectSchema<serializers.ArtifactsGetResponse.Raw, DevrevApi.ArtifactsGetResponse>;
export declare namespace ArtifactsGetResponse {
    interface Raw {
        artifact: serializers.Artifact.Raw;
        version: serializers.ArtifactVersion.Raw;
    }
}
