/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ArtifactVersion: core.serialization.ObjectSchema<serializers.ArtifactVersion.Raw, DevrevApi.ArtifactVersion>;
export declare namespace ArtifactVersion {
    interface Raw {
        modified_by?: serializers.UserSummary.Raw | null;
        timestamp: string;
        version: string;
    }
}
