/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Artifact: core.serialization.ObjectSchema<serializers.Artifact.Raw, DevrevApi.Artifact>;
export declare namespace Artifact {
    type Raw = serializers.AtomBase.Raw;
}
