/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ArtifactsPrepareResponse: core.serialization.ObjectSchema<serializers.ArtifactsPrepareResponse.Raw, DevrevApi.ArtifactsPrepareResponse>;
export declare namespace ArtifactsPrepareResponse {
    interface Raw {
        form_data: serializers.ArtifactsPrepareResponseFormData.Raw[];
        id: string;
        url: string;
    }
}
