/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ArtifactSummary: core.serialization.ObjectSchema<serializers.ArtifactSummary.Raw, DevrevApi.ArtifactSummary>;
export declare namespace ArtifactSummary {
    type Raw = serializers.AtomBaseSummary.Raw;
}
