/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AtomBase: core.serialization.ObjectSchema<serializers.AtomBase.Raw, DevrevApi.AtomBase>;
export declare namespace AtomBase {
    interface Raw {
        created_by?: serializers.UserSummary.Raw | null;
        created_date?: string | null;
        display_id?: string | null;
        id: string;
        modified_by?: serializers.UserSummary.Raw | null;
        modified_date?: string | null;
    }
}
