/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthTokensUserTraits: core.serialization.ObjectSchema<serializers.AuthTokensUserTraits.Raw, DevrevApi.AuthTokensUserTraits>;
export declare namespace AuthTokensUserTraits {
    interface Raw {
        custom_fields?: Record<string, unknown> | null;
        description?: string | null;
        display_name?: string | null;
        email?: string | null;
        full_name?: string | null;
        phone_numbers?: string[] | null;
    }
}
