/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthConnectionOptionsOidc: core.serialization.ObjectSchema<serializers.AuthConnectionOptionsOidc.Raw, DevrevApi.AuthConnectionOptionsOidc>;
export declare namespace AuthConnectionOptionsOidc {
    interface Raw {
        client_id?: string | null;
        client_secret?: string | null;
        issuer?: string | null;
    }
}
