/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthTokensGetResponse: core.serialization.ObjectSchema<serializers.AuthTokensGetResponse.Raw, DevrevApi.AuthTokensGetResponse>;
export declare namespace AuthTokensGetResponse {
    interface Raw {
        token: serializers.AuthToken.Raw;
    }
}
