/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthTokensOrgTraits: core.serialization.ObjectSchema<serializers.AuthTokensOrgTraits.Raw, DevrevApi.AuthTokensOrgTraits>;
export declare namespace AuthTokensOrgTraits {
    interface Raw {
        custom_fields?: Record<string, unknown> | null;
        description?: string | null;
        display_name?: string | null;
        domain?: string | null;
        phone_numbers?: string[] | null;
        tier?: string | null;
    }
}
