/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthToken: core.serialization.ObjectSchema<serializers.AuthToken.Raw, DevrevApi.AuthToken>;
export declare namespace AuthToken {
    interface Raw extends serializers.AtomBase.Raw {
        client_id?: string | null;
        expires_at?: string | null;
        issued_at?: string | null;
        requested_token_type?: serializers.AuthTokenRequestedTokenType.Raw | null;
        scopes?: string[] | null;
        status?: serializers.AuthTokenStatus.Raw | null;
        subject?: string | null;
        token_hint?: string | null;
    }
}
