/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthConnectionToggle: core.serialization.Schema<serializers.AuthConnectionToggle.Raw, DevrevApi.AuthConnectionToggle>;
export declare namespace AuthConnectionToggle {
    type Raw = "disable" | "enable";
}
