/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthConnectionOptionsGoogleApps: core.serialization.ObjectSchema<serializers.AuthConnectionOptionsGoogleApps.Raw, DevrevApi.AuthConnectionOptionsGoogleApps>;
export declare namespace AuthConnectionOptionsGoogleApps {
    interface Raw {
        client_id?: string | null;
        client_secret?: string | null;
        tenant_domain?: string | null;
    }
}
