/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthTokensListResponse: core.serialization.ObjectSchema<serializers.AuthTokensListResponse.Raw, DevrevApi.AuthTokensListResponse>;
export declare namespace AuthTokensListResponse {
    interface Raw {
        tokens: serializers.AuthToken.Raw[];
    }
}
