/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthConnectionOptionsSocial: core.serialization.Schema<serializers.AuthConnectionOptionsSocial.Raw, DevrevApi.AuthConnectionOptionsSocial>;
export declare namespace AuthConnectionOptionsSocial {
    type Raw = Record<string, unknown>;
}
