/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthTokenSubjectTokenType: core.serialization.Schema<serializers.AuthTokenSubjectTokenType.Raw, DevrevApi.AuthTokenSubjectTokenType>;
export declare namespace AuthTokenSubjectTokenType {
    type Raw = "urn:devrev:params:oauth:token-type:jwt:auth0" | "urn:devrev:params:oauth:token-type:jwt:dev" | "urn:devrev:params:oauth:token-type:rat" | "urn:devrev:params:oauth:token-type:revinfo" | "urn:devrev:params:oauth:token-type:session" | "urn:devrev:params:oauth:token-type:sysu" | "urn:devrev:params:oauth:token-type:userinfo" | "urn:devrev:params:oauth:token-type:userinfo:profile" | "urn:ietf:params:oauth:token-type:jwt";
}
