/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthConnectionOptionsAzureAd: core.serialization.ObjectSchema<serializers.AuthConnectionOptionsAzureAd.Raw, DevrevApi.AuthConnectionOptionsAzureAd>;
export declare namespace AuthConnectionOptionsAzureAd {
    interface Raw {
        client_id?: string | null;
        client_secret?: string | null;
        domain?: string | null;
    }
}
