/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthTokensCreateResponse: core.serialization.ObjectSchema<serializers.AuthTokensCreateResponse.Raw, DevrevApi.AuthTokensCreateResponse>;
export declare namespace AuthTokensCreateResponse {
    interface Raw {
        access_token: string;
        client_id?: string | null;
        expires_in: number;
        refresh_token?: string | null;
        scope?: string | null;
        token_type: serializers.AuthTokenTokenType.Raw;
    }
}
