/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const AuthConnectionType: core.serialization.Schema<serializers.AuthConnectionType.Raw, DevrevApi.AuthConnectionType>;
export declare namespace AuthConnectionType {
    type Raw = "google_apps" | "oidc" | "samlp" | "social" | "waad";
}
