/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import * as serializers from "..";
import * as DevrevApi from "../../api";
export declare const AuthConnection: core.serialization.Schema<serializers.AuthConnection.Raw, DevrevApi.AuthConnection>;
export declare namespace AuthConnection {
    type Raw = AuthConnection.GoogleApps | AuthConnection.Oidc | AuthConnection.Samlp | AuthConnection.Social | AuthConnection.Waad;
    interface GoogleApps extends _Base, serializers.AuthConnectionOptionsGoogleApps.Raw {
        type: "google_apps";
    }
    interface Oidc extends _Base, serializers.AuthConnectionOptionsOidc.Raw {
        type: "oidc";
    }
    interface Samlp extends _Base, serializers.AuthConnectionOptionsSaml.Raw {
        type: "samlp";
    }
    interface Social extends _Base {
        type: "social";
        value: serializers.AuthConnectionOptionsSocial.Raw;
    }
    interface Waad extends _Base, serializers.AuthConnectionOptionsAzureAd.Raw {
        type: "waad";
    }
    interface _Base {
        display_name?: string | null;
        enabled?: boolean | null;
        id: string;
    }
}
