/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Capability: core.serialization.ObjectSchema<serializers.Capability.Raw, DevrevApi.Capability>;
export declare namespace Capability {
    type Raw = serializers.PartBase.Raw;
}
