/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const CapabilitySummary: core.serialization.ObjectSchema<serializers.CapabilitySummary.Raw, DevrevApi.CapabilitySummary>;
export declare namespace CapabilitySummary {
    type Raw = serializers.PartBaseSummary.Raw;
}
