/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DateFilter: core.serialization.Schema<serializers.DateFilter.Raw, DevrevApi.DateFilter>;
export declare namespace DateFilter {
    type Raw = DateFilter.Preset | DateFilter.Range;
    interface Preset {
        type: "preset";
        value: serializers.DateTimePreset.Raw;
    }
    interface Range extends serializers.DateTimeFilter.Raw {
        type: "range";
    }
}
