/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DateTimePresetLastNDays: core.serialization.ObjectSchema<serializers.DateTimePresetLastNDays.Raw, DevrevApi.DateTimePresetLastNDays>;
export declare namespace DateTimePresetLastNDays {
    interface Raw {
        days: number;
    }
}
