/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DateTimePresetNextNDays: core.serialization.ObjectSchema<serializers.DateTimePresetNextNDays.Raw, DevrevApi.DateTimePresetNextNDays>;
export declare namespace DateTimePresetNextNDays {
    interface Raw {
        days: number;
    }
}
