/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DevOrgAuthConnectionsCreateResponse: core.serialization.ObjectSchema<serializers.DevOrgAuthConnectionsCreateResponse.Raw, DevrevApi.DevOrgAuthConnectionsCreateResponse>;
export declare namespace DevOrgAuthConnectionsCreateResponse {
    interface Raw {
        auth_connection: serializers.AuthConnection.Raw;
    }
}
