/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DevOrgAuthConnectionsUpdateResponse: core.serialization.ObjectSchema<serializers.DevOrgAuthConnectionsUpdateResponse.Raw, DevrevApi.DevOrgAuthConnectionsUpdateResponse>;
export declare namespace DevOrgAuthConnectionsUpdateResponse {
    interface Raw {
        auth_connection: serializers.AuthConnection.Raw;
    }
}
