/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DevOrgAuthConnectionsCreateRequestType: core.serialization.Schema<serializers.DevOrgAuthConnectionsCreateRequestType.Raw, DevrevApi.DevOrgAuthConnectionsCreateRequestType>;
export declare namespace DevOrgAuthConnectionsCreateRequestType {
    type Raw = "google_apps" | "oidc" | "samlp" | "waad";
}
