/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DevUsersSelfRequest: core.serialization.Schema<serializers.DevUsersSelfRequest.Raw, DevrevApi.DevUsersSelfRequest>;
export declare namespace DevUsersSelfRequest {
    type Raw = Record<string, unknown>;
}
