/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DevUser: core.serialization.ObjectSchema<serializers.DevUser.Raw, DevrevApi.DevUser>;
export declare namespace DevUser {
    interface Raw extends serializers.UserBase.Raw {
        external_identities?: serializers.ExternalIdentity.Raw[] | null;
    }
}
