/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const DevUserExternalIdentityFilter: core.serialization.ObjectSchema<serializers.DevUserExternalIdentityFilter.Raw, DevrevApi.DevUserExternalIdentityFilter>;
export declare namespace DevUserExternalIdentityFilter {
    interface Raw {
        id?: string | null;
        issuer?: string | null;
    }
}
