/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Empty: core.serialization.Schema<serializers.Empty.Raw, DevrevApi.Empty>;
export declare namespace Empty {
    type Raw = Record<string, unknown>;
}
