/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorBadRequestInvalidApiVersion: core.serialization.ObjectSchema<serializers.ErrorBadRequestInvalidApiVersion.Raw, DevrevApi.ErrorBadRequestInvalidApiVersion>;
export declare namespace ErrorBadRequestInvalidApiVersion {
    interface Raw {
        value: string;
    }
}
