/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorNotFoundNotFound: core.serialization.Schema<serializers.ErrorNotFoundNotFound.Raw, DevrevApi.ErrorNotFoundNotFound>;
export declare namespace ErrorNotFoundNotFound {
    type Raw = Record<string, unknown>;
}
