/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorTooManyRequestsType: core.serialization.Schema<serializers.ErrorTooManyRequestsType.Raw, DevrevApi.ErrorTooManyRequestsType>;
export declare namespace ErrorTooManyRequestsType {
    type Raw = "too_many_requests";
}
