/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorConflict: core.serialization.ObjectSchema<serializers.ErrorConflict.Raw, DevrevApi.ErrorConflict>;
export declare namespace ErrorConflict {
    interface Raw extends serializers.ErrorBase.Raw {
    }
}
