/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorInternalServerErrorType: core.serialization.Schema<serializers.ErrorInternalServerErrorType.Raw, DevrevApi.ErrorInternalServerErrorType>;
export declare namespace ErrorInternalServerErrorType {
    type Raw = "internal_error";
}
