/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorServiceUnavailableServiceUnavailable: core.serialization.Schema<serializers.ErrorServiceUnavailableServiceUnavailable.Raw, DevrevApi.ErrorServiceUnavailableServiceUnavailable>;
export declare namespace ErrorServiceUnavailableServiceUnavailable {
    type Raw = Record<string, unknown>;
}
