/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorNotFoundType: core.serialization.Schema<serializers.ErrorNotFoundType.Raw, DevrevApi.ErrorNotFoundType>;
export declare namespace ErrorNotFoundType {
    type Raw = "not_found";
}
