/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorBadRequestBadRequest: core.serialization.Schema<serializers.ErrorBadRequestBadRequest.Raw, DevrevApi.ErrorBadRequestBadRequest>;
export declare namespace ErrorBadRequestBadRequest {
    type Raw = Record<string, unknown>;
}
