/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorBadRequestMissingRequiredField: core.serialization.ObjectSchema<serializers.ErrorBadRequestMissingRequiredField.Raw, DevrevApi.ErrorBadRequestMissingRequiredField>;
export declare namespace ErrorBadRequestMissingRequiredField {
    interface Raw {
        field_name: string;
    }
}
