/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorForbidden: core.serialization.ObjectSchema<serializers.ErrorForbidden.Raw, DevrevApi.ErrorForbidden>;
export declare namespace ErrorForbidden {
    interface Raw extends serializers.ErrorBase.Raw {
    }
}
