/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorForbiddenForbidden: core.serialization.Schema<serializers.ErrorForbiddenForbidden.Raw, DevrevApi.ErrorForbiddenForbidden>;
export declare namespace ErrorForbiddenForbidden {
    type Raw = Record<string, unknown>;
}
