/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorBase: core.serialization.ObjectSchema<serializers.ErrorBase.Raw, DevrevApi.ErrorBase>;
export declare namespace ErrorBase {
    interface Raw {
        detail?: string | null;
        message?: string | null;
    }
}
