/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorForbiddenType: core.serialization.Schema<serializers.ErrorForbiddenType.Raw, DevrevApi.ErrorForbiddenType>;
export declare namespace ErrorForbiddenType {
    type Raw = "forbidden";
}
