/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorBadRequestInvalidField: core.serialization.ObjectSchema<serializers.ErrorBadRequestInvalidField.Raw, DevrevApi.ErrorBadRequestInvalidField>;
export declare namespace ErrorBadRequestInvalidField {
    interface Raw {
        field_name: string;
    }
}
