/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorUnauthorized: core.serialization.ObjectSchema<serializers.ErrorUnauthorized.Raw, DevrevApi.ErrorUnauthorized>;
export declare namespace ErrorUnauthorized {
    interface Raw extends serializers.ErrorBase.Raw {
    }
}
