/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorInternalServerError: core.serialization.ObjectSchema<serializers.ErrorInternalServerError.Raw, DevrevApi.ErrorInternalServerError>;
export declare namespace ErrorInternalServerError {
    interface Raw extends serializers.ErrorBase.Raw {
    }
}
