/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorBadRequestMissingDependencyDependency: core.serialization.ObjectSchema<serializers.ErrorBadRequestMissingDependencyDependency.Raw, DevrevApi.ErrorBadRequestMissingDependencyDependency>;
export declare namespace ErrorBadRequestMissingDependencyDependency {
    interface Raw {
        field_name: string;
        field_value: string;
    }
}
