/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorTooManyRequestsTooManyRequests: core.serialization.Schema<serializers.ErrorTooManyRequestsTooManyRequests.Raw, DevrevApi.ErrorTooManyRequestsTooManyRequests>;
export declare namespace ErrorTooManyRequestsTooManyRequests {
    type Raw = Record<string, unknown>;
}
