/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ErrorBadRequestValueNotPermitted: core.serialization.ObjectSchema<serializers.ErrorBadRequestValueNotPermitted.Raw, DevrevApi.ErrorBadRequestValueNotPermitted>;
export declare namespace ErrorBadRequestValueNotPermitted {
    interface Raw {
        allowed_values?: string[] | null;
        field_name: string;
        reason?: string | null;
    }
}
