/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventDevUserCreated: core.serialization.ObjectSchema<serializers.EventDevUserCreated.Raw, DevrevApi.EventDevUserCreated>;
export declare namespace EventDevUserCreated {
    interface Raw {
        dev_user: serializers.DevUser.Raw;
    }
}
