/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventRevOrgDeleted: core.serialization.ObjectSchema<serializers.EventRevOrgDeleted.Raw, DevrevApi.EventRevOrgDeleted>;
export declare namespace EventRevOrgDeleted {
    interface Raw {
        id: string;
    }
}
