/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventDevUserDeleted: core.serialization.ObjectSchema<serializers.EventDevUserDeleted.Raw, DevrevApi.EventDevUserDeleted>;
export declare namespace EventDevUserDeleted {
    interface Raw {
        id: string;
    }
}
