/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventPartCreated: core.serialization.ObjectSchema<serializers.EventPartCreated.Raw, DevrevApi.EventPartCreated>;
export declare namespace EventPartCreated {
    interface Raw {
        part: serializers.Part.Raw;
    }
}
