/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventSlaTrackerDeleted: core.serialization.ObjectSchema<serializers.EventSlaTrackerDeleted.Raw, DevrevApi.EventSlaTrackerDeleted>;
export declare namespace EventSlaTrackerDeleted {
    interface Raw {
        id: string;
    }
}
