/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventConversationCreated: core.serialization.ObjectSchema<serializers.EventConversationCreated.Raw, DevrevApi.EventConversationCreated>;
export declare namespace EventConversationCreated {
    interface Raw {
        conversation: serializers.Conversation.Raw;
    }
}
