/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventRevUserDeleted: core.serialization.ObjectSchema<serializers.EventRevUserDeleted.Raw, DevrevApi.EventRevUserDeleted>;
export declare namespace EventRevUserDeleted {
    interface Raw {
        id: string;
    }
}
