/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventWorkCreated: core.serialization.ObjectSchema<serializers.EventWorkCreated.Raw, DevrevApi.EventWorkCreated>;
export declare namespace EventWorkCreated {
    interface Raw {
        work: serializers.Work.Raw;
    }
}
