/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventConversationDeleted: core.serialization.ObjectSchema<serializers.EventConversationDeleted.Raw, DevrevApi.EventConversationDeleted>;
export declare namespace EventConversationDeleted {
    interface Raw {
        id: string;
    }
}
