/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventDevUserUpdated: core.serialization.ObjectSchema<serializers.EventDevUserUpdated.Raw, DevrevApi.EventDevUserUpdated>;
export declare namespace EventDevUserUpdated {
    interface Raw {
        dev_user: serializers.DevUser.Raw;
    }
}
