/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventWebhookDeleted: core.serialization.ObjectSchema<serializers.EventWebhookDeleted.Raw, DevrevApi.EventWebhookDeleted>;
export declare namespace EventWebhookDeleted {
    interface Raw {
        id: string;
    }
}
