/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventWorkDeleted: core.serialization.ObjectSchema<serializers.EventWorkDeleted.Raw, DevrevApi.EventWorkDeleted>;
export declare namespace EventWorkDeleted {
    interface Raw {
        id: string;
    }
}
