/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventSlaTrackerUpdated: core.serialization.ObjectSchema<serializers.EventSlaTrackerUpdated.Raw, DevrevApi.EventSlaTrackerUpdated>;
export declare namespace EventSlaTrackerUpdated {
    interface Raw {
        sla_tracker: serializers.SlaTracker.Raw;
    }
}
