/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventTimelineEntryDeleted: core.serialization.ObjectSchema<serializers.EventTimelineEntryDeleted.Raw, DevrevApi.EventTimelineEntryDeleted>;
export declare namespace EventTimelineEntryDeleted {
    interface Raw {
        id: string;
    }
}
