/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventRevOrgCreated: core.serialization.ObjectSchema<serializers.EventRevOrgCreated.Raw, DevrevApi.EventRevOrgCreated>;
export declare namespace EventRevOrgCreated {
    interface Raw {
        rev_org: serializers.RevOrg.Raw;
    }
}
