/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventSurveyResponseCreated: core.serialization.ObjectSchema<serializers.EventSurveyResponseCreated.Raw, DevrevApi.EventSurveyResponseCreated>;
export declare namespace EventSurveyResponseCreated {
    interface Raw {
        survey_response: serializers.SurveyResponse.Raw;
    }
}
