/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventAccountCreated: core.serialization.ObjectSchema<serializers.EventAccountCreated.Raw, DevrevApi.EventAccountCreated>;
export declare namespace EventAccountCreated {
    interface Raw {
        account: serializers.Account.Raw;
    }
}
