/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const EventTimelineEntryCreated: core.serialization.ObjectSchema<serializers.EventTimelineEntryCreated.Raw, DevrevApi.EventTimelineEntryCreated>;
export declare namespace EventTimelineEntryCreated {
    interface Raw {
        entry: serializers.TimelineEntry.Raw;
    }
}
