/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ExternalIdentity: core.serialization.Schema<serializers.ExternalIdentity.Raw, DevrevApi.ExternalIdentity>;
export declare namespace ExternalIdentity {
    type Raw = Record<string, unknown>;
}
