/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const FeatureSummary: core.serialization.ObjectSchema<serializers.FeatureSummary.Raw, DevrevApi.FeatureSummary>;
export declare namespace FeatureSummary {
    type Raw = serializers.PartBaseSummary.Raw;
}
