/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Feature: core.serialization.ObjectSchema<serializers.Feature.Raw, DevrevApi.Feature>;
export declare namespace Feature {
    type Raw = serializers.PartBase.Raw;
}
