/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Issue: core.serialization.ObjectSchema<serializers.Issue.Raw, DevrevApi.Issue>;
export declare namespace Issue {
    interface Raw extends serializers.WorkBase.Raw {
        developed_with?: serializers.PartSummary.Raw[] | null;
        priority?: serializers.IssuePriority.Raw | null;
        target_start_date?: string | null;
    }
}
