/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const MetricDefinitionSummary: core.serialization.ObjectSchema<serializers.MetricDefinitionSummary.Raw, DevrevApi.MetricDefinitionSummary>;
export declare namespace MetricDefinitionSummary {
    interface Raw extends serializers.AtomBaseSummary.Raw {
        name?: string | null;
    }
}
