/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const OrgBase: core.serialization.ObjectSchema<serializers.OrgBase.Raw, DevrevApi.OrgBase>;
export declare namespace OrgBase {
    interface Raw extends serializers.AtomBase.Raw {
        display_name?: string | null;
    }
}
