/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const OrgBaseSummary: core.serialization.ObjectSchema<serializers.OrgBaseSummary.Raw, DevrevApi.OrgBaseSummary>;
export declare namespace OrgBaseSummary {
    interface Raw extends serializers.AtomBaseSummary.Raw {
        display_name?: string | null;
    }
}
