/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const OrgScheduleStatus: core.serialization.Schema<serializers.OrgScheduleStatus.Raw, DevrevApi.OrgScheduleStatus>;
export declare namespace OrgScheduleStatus {
    type Raw = "archived" | "draft" | "published";
}
