/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const OrgSummary: core.serialization.Schema<serializers.OrgSummary.Raw, DevrevApi.OrgSummary>;
export declare namespace OrgSummary {
    type Raw = OrgSummary.RevOrg;
    interface RevOrg extends serializers.OrgBaseSummary.Raw {
        type: "rev_org";
    }
}
