/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const OrgType: core.serialization.Schema<serializers.OrgType.Raw, DevrevApi.OrgType>;
export declare namespace OrgType {
    type Raw = "rev_org";
}
