/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ParentPartFilter: core.serialization.ObjectSchema<serializers.ParentPartFilter.Raw, DevrevApi.ParentPartFilter>;
export declare namespace ParentPartFilter {
    interface Raw {
        level?: number | null;
        parts: string[];
    }
}
