/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsGetResponse: core.serialization.ObjectSchema<serializers.PartsGetResponse.Raw, DevrevApi.PartsGetResponse>;
export declare namespace PartsGetResponse {
    interface Raw {
        part: serializers.Part.Raw;
    }
}
