/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsUpdateRequestEnhancement: core.serialization.ObjectSchema<serializers.PartsUpdateRequestEnhancement.Raw, DevrevApi.PartsUpdateRequestEnhancement>;
export declare namespace PartsUpdateRequestEnhancement {
    interface Raw {
        target_close_date?: string | null;
        target_start_date?: string | null;
    }
}
