/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsUpdateResponse: core.serialization.ObjectSchema<serializers.PartsUpdateResponse.Raw, DevrevApi.PartsUpdateResponse>;
export declare namespace PartsUpdateResponse {
    interface Raw {
        part: serializers.Part.Raw;
    }
}
