/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsCreateRequestFeature: core.serialization.ObjectSchema<serializers.PartsCreateRequestFeature.Raw, DevrevApi.PartsCreateRequestFeature>;
export declare namespace PartsCreateRequestFeature {
    interface Raw {
        parent_part: string[];
    }
}
