/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsUpdateRequestProduct: core.serialization.Schema<serializers.PartsUpdateRequestProduct.Raw, DevrevApi.PartsUpdateRequestProduct>;
export declare namespace PartsUpdateRequestProduct {
    type Raw = Record<string, unknown>;
}
