/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartSummary: core.serialization.Schema<serializers.PartSummary.Raw, DevrevApi.PartSummary>;
export declare namespace PartSummary {
    type Raw = PartSummary.Capability | PartSummary.Enhancement | PartSummary.Feature | PartSummary.Product;
    interface Capability extends serializers.PartBaseSummary.Raw {
        type: "capability";
    }
    interface Enhancement extends serializers.PartBaseSummary.Raw {
        type: "enhancement";
    }
    interface Feature extends serializers.PartBaseSummary.Raw {
        type: "feature";
    }
    interface Product extends serializers.PartBaseSummary.Raw {
        type: "product";
    }
}
