/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsUpdateRequestArtifacts: core.serialization.ObjectSchema<serializers.PartsUpdateRequestArtifacts.Raw, DevrevApi.PartsUpdateRequestArtifacts>;
export declare namespace PartsUpdateRequestArtifacts {
    interface Raw {
        set?: string[] | null;
    }
}
