/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsUpdateRequestFeature: core.serialization.Schema<serializers.PartsUpdateRequestFeature.Raw, DevrevApi.PartsUpdateRequestFeature>;
export declare namespace PartsUpdateRequestFeature {
    type Raw = Record<string, unknown>;
}
