/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsCreateRequestProduct: core.serialization.Schema<serializers.PartsCreateRequestProduct.Raw, DevrevApi.PartsCreateRequestProduct>;
export declare namespace PartsCreateRequestProduct {
    type Raw = Record<string, unknown>;
}
