/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import * as serializers from "..";
import * as DevrevApi from "../../api";
export declare const PartsCreateRequest: core.serialization.Schema<serializers.PartsCreateRequest.Raw, DevrevApi.PartsCreateRequest>;
export declare namespace PartsCreateRequest {
    type Raw = PartsCreateRequest.Capability | PartsCreateRequest.Enhancement | PartsCreateRequest.Feature | PartsCreateRequest.Product;
    interface Capability extends _Base, serializers.PartsCreateRequestCapability.Raw {
        type: "capability";
    }
    interface Enhancement extends _Base, serializers.PartsCreateRequestEnhancement.Raw {
        type: "enhancement";
    }
    interface Feature extends _Base, serializers.PartsCreateRequestFeature.Raw {
        type: "feature";
    }
    interface Product extends _Base {
        type: "product";
        value: serializers.PartsCreateRequestProduct.Raw;
    }
    interface _Base {
        artifacts?: string[] | null;
        description?: string | null;
        name: string;
        owned_by: string[];
    }
}
