/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsUpdateRequestCapability: core.serialization.Schema<serializers.PartsUpdateRequestCapability.Raw, DevrevApi.PartsUpdateRequestCapability>;
export declare namespace PartsUpdateRequestCapability {
    type Raw = Record<string, unknown>;
}
