/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartBase: core.serialization.ObjectSchema<serializers.PartBase.Raw, DevrevApi.PartBase>;
export declare namespace PartBase {
    interface Raw extends serializers.AtomBase.Raw {
        artifacts?: serializers.ArtifactSummary.Raw[] | null;
        description?: string | null;
        name: string;
        owned_by: serializers.UserSummary.Raw[];
        tags?: serializers.TagWithValue.Raw[] | null;
    }
}
