/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsCreateResponse: core.serialization.ObjectSchema<serializers.PartsCreateResponse.Raw, DevrevApi.PartsCreateResponse>;
export declare namespace PartsCreateResponse {
    interface Raw {
        part: serializers.Part.Raw;
    }
}
