/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsCreateRequestCapability: core.serialization.ObjectSchema<serializers.PartsCreateRequestCapability.Raw, DevrevApi.PartsCreateRequestCapability>;
export declare namespace PartsCreateRequestCapability {
    interface Raw {
        parent_part: string[];
    }
}
