/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const PartsListResponse: core.serialization.ObjectSchema<serializers.PartsListResponse.Raw, DevrevApi.PartsListResponse>;
export declare namespace PartsListResponse {
    interface Raw {
        next_cursor?: string | null;
        parts: serializers.Part.Raw[];
        prev_cursor?: string | null;
    }
}
