/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Product: core.serialization.ObjectSchema<serializers.Product.Raw, DevrevApi.Product>;
export declare namespace Product {
    type Raw = serializers.PartBase.Raw;
}
