/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const ProductSummary: core.serialization.ObjectSchema<serializers.ProductSummary.Raw, DevrevApi.ProductSummary>;
export declare namespace ProductSummary {
    type Raw = serializers.PartBaseSummary.Raw;
}
