/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const RevOrgsDeleteResponse: core.serialization.Schema<serializers.RevOrgsDeleteResponse.Raw, DevrevApi.RevOrgsDeleteResponse>;
export declare namespace RevOrgsDeleteResponse {
    type Raw = Record<string, unknown>;
}
