/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const RevOrgSummary: core.serialization.ObjectSchema<serializers.RevOrgSummary.Raw, DevrevApi.RevOrgSummary>;
export declare namespace RevOrgSummary {
    type Raw = serializers.OrgBaseSummary.Raw;
}
