/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const RevOrgsCreateResponse: core.serialization.ObjectSchema<serializers.RevOrgsCreateResponse.Raw, DevrevApi.RevOrgsCreateResponse>;
export declare namespace RevOrgsCreateResponse {
    interface Raw {
        rev_org: serializers.RevOrg.Raw;
    }
}
