/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const RevOrgsGetResponse: core.serialization.ObjectSchema<serializers.RevOrgsGetResponse.Raw, DevrevApi.RevOrgsGetResponse>;
export declare namespace RevOrgsGetResponse {
    interface Raw {
        rev_org: serializers.RevOrg.Raw;
    }
}
