/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const RevOrgsListResponse: core.serialization.ObjectSchema<serializers.RevOrgsListResponse.Raw, DevrevApi.RevOrgsListResponse>;
export declare namespace RevOrgsListResponse {
    interface Raw {
        next_cursor?: string | null;
        prev_cursor?: string | null;
        rev_orgs: serializers.RevOrg.Raw[];
    }
}
