/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const RevUser: core.serialization.ObjectSchema<serializers.RevUser.Raw, DevrevApi.RevUser>;
export declare namespace RevUser {
    interface Raw extends serializers.UserBase.Raw {
        description?: string | null;
        external_ref?: string | null;
        rev_org?: serializers.OrgSummary.Raw | null;
    }
}
