/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const RevUserSummary: core.serialization.ObjectSchema<serializers.RevUserSummary.Raw, DevrevApi.RevUserSummary>;
export declare namespace RevUserSummary {
    interface Raw extends serializers.UserBaseSummary.Raw {
        external_ref?: string | null;
        rev_org?: serializers.OrgSummary.Raw | null;
    }
}
