/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const SlaTrackersGetResponse: core.serialization.ObjectSchema<serializers.SlaTrackersGetResponse.Raw, DevrevApi.SlaTrackersGetResponse>;
export declare namespace SlaTrackersGetResponse {
    interface Raw {
        sla_tracker: serializers.SlaTracker.Raw;
    }
}
