/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const SlaTracker: core.serialization.ObjectSchema<serializers.SlaTracker.Raw, DevrevApi.SlaTracker>;
export declare namespace SlaTracker {
    interface Raw extends serializers.AtomBase.Raw {
        applies_to_id?: string | null;
        metric_target_summaries: serializers.ArchetypeMetricTarget.Raw[];
        sla?: serializers.SlaSummary.Raw | null;
        sla_policy_id?: string | null;
        stage?: string | null;
        status?: string | null;
    }
}
