/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const StageFilter: core.serialization.ObjectSchema<serializers.StageFilter.Raw, DevrevApi.StageFilter>;
export declare namespace StageFilter {
    interface Raw {
        name?: string[] | null;
    }
}
