/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const StagedInfoFilter: core.serialization.ObjectSchema<serializers.StagedInfoFilter.Raw, DevrevApi.StagedInfoFilter>;
export declare namespace StagedInfoFilter {
    interface Raw {
        is_staged?: boolean | null;
    }
}
