/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const StageInit: core.serialization.ObjectSchema<serializers.StageInit.Raw, DevrevApi.StageInit>;
export declare namespace StageInit {
    interface Raw {
        name?: string | null;
    }
}
