/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const SyncMetadataFilterSyncInFilterStatus: core.serialization.Schema<serializers.SyncMetadataFilterSyncInFilterStatus.Raw, DevrevApi.SyncMetadataFilterSyncInFilterStatus>;
export declare namespace SyncMetadataFilterSyncInFilterStatus {
    type Raw = "failed" | "modified" | "staged" | "succeeded";
}
