/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const SyncMetadataFilterSyncInFilter: core.serialization.ObjectSchema<serializers.SyncMetadataFilterSyncInFilter.Raw, DevrevApi.SyncMetadataFilterSyncInFilter>;
export declare namespace SyncMetadataFilterSyncInFilter {
    interface Raw {
        status?: serializers.SyncMetadataFilterSyncInFilterStatus.Raw[] | null;
        sync_date?: serializers.DateFilter.Raw | null;
        sync_unit?: string[] | null;
    }
}
