/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const SyncMetadataFilterSyncOutFilterStatus: core.serialization.Schema<serializers.SyncMetadataFilterSyncOutFilterStatus.Raw, DevrevApi.SyncMetadataFilterSyncOutFilterStatus>;
export declare namespace SyncMetadataFilterSyncOutFilterStatus {
    type Raw = "failed" | "succeeded";
}
