/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const SysUserSummary: core.serialization.ObjectSchema<serializers.SysUserSummary.Raw, DevrevApi.SysUserSummary>;
export declare namespace SysUserSummary {
    type Raw = serializers.UserBaseSummary.Raw;
}
