/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TagsDeleteResponse: core.serialization.Schema<serializers.TagsDeleteResponse.Raw, DevrevApi.TagsDeleteResponse>;
export declare namespace TagsDeleteResponse {
    type Raw = Record<string, unknown>;
}
