/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TagsUpdateAllowedValues: core.serialization.ObjectSchema<serializers.TagsUpdateAllowedValues.Raw, DevrevApi.TagsUpdateAllowedValues>;
export declare namespace TagsUpdateAllowedValues {
    interface Raw {
        set?: string[] | null;
    }
}
