/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TagsUpdateResponse: core.serialization.ObjectSchema<serializers.TagsUpdateResponse.Raw, DevrevApi.TagsUpdateResponse>;
export declare namespace TagsUpdateResponse {
    interface Raw {
        tag: serializers.Tag.Raw;
    }
}
