/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TagsGetResponse: core.serialization.ObjectSchema<serializers.TagsGetResponse.Raw, DevrevApi.TagsGetResponse>;
export declare namespace TagsGetResponse {
    interface Raw {
        tag: serializers.Tag.Raw;
    }
}
