/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TagWithValue: core.serialization.ObjectSchema<serializers.TagWithValue.Raw, DevrevApi.TagWithValue>;
export declare namespace TagWithValue {
    interface Raw {
        tag: serializers.TagSummary.Raw;
        value?: string | null;
    }
}
