/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Ticket: core.serialization.ObjectSchema<serializers.Ticket.Raw, DevrevApi.Ticket>;
export declare namespace Ticket {
    interface Raw extends serializers.WorkBase.Raw {
        channels?: serializers.TicketChannels.Raw[] | null;
        group?: serializers.GroupSummary.Raw | null;
        rev_org?: serializers.OrgSummary.Raw | null;
        severity?: serializers.TicketSeverity.Raw | null;
        sla_tracker?: serializers.SlaTrackerSummary.Raw | null;
        source_channel?: string | null;
    }
}
