/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TicketChannels: core.serialization.Schema<serializers.TicketChannels.Raw, DevrevApi.TicketChannels>;
export declare namespace TicketChannels {
    type Raw = "email" | "plug" | "slack";
}
