/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntriesUpdateRequestTimelineCommentArtifacts: core.serialization.ObjectSchema<serializers.TimelineEntriesUpdateRequestTimelineCommentArtifacts.Raw, DevrevApi.TimelineEntriesUpdateRequestTimelineCommentArtifacts>;
export declare namespace TimelineEntriesUpdateRequestTimelineCommentArtifacts {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
        set?: string[] | null;
    }
}
