/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineCommentBodyType: core.serialization.Schema<serializers.TimelineCommentBodyType.Raw, DevrevApi.TimelineCommentBodyType>;
export declare namespace TimelineCommentBodyType {
    type Raw = "snap_kit" | "snap_widget" | "text";
}
