/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntriesCreateResponse: core.serialization.ObjectSchema<serializers.TimelineEntriesCreateResponse.Raw, DevrevApi.TimelineEntriesCreateResponse>;
export declare namespace TimelineEntriesCreateResponse {
    interface Raw {
        timeline_entry: serializers.TimelineEntry.Raw;
    }
}
