/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntry: core.serialization.Schema<serializers.TimelineEntry.Raw, DevrevApi.TimelineEntry>;
export declare namespace TimelineEntry {
    type Raw = TimelineEntry.TimelineComment;
    interface TimelineComment extends serializers.TimelineComment.Raw {
        type: "timeline_comment";
    }
}
