/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntryBase: core.serialization.ObjectSchema<serializers.TimelineEntryBase.Raw, DevrevApi.TimelineEntryBase>;
export declare namespace TimelineEntryBase {
    interface Raw extends serializers.AtomBase.Raw {
        object: string;
        object_display_id: string;
        object_type?: serializers.TimelineEntryObjectType.Raw | null;
        visibility?: serializers.TimelineEntryVisibility.Raw | null;
    }
}
