/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntryObjectType: core.serialization.Schema<serializers.TimelineEntryObjectType.Raw, DevrevApi.TimelineEntryObjectType>;
export declare namespace TimelineEntryObjectType {
    type Raw = "capability" | "conversation" | "enhancement" | "feature" | "issue" | "product" | "rev_org" | "rev_user" | "ticket" | "timeline_comment";
}
