/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntriesGetResponse: core.serialization.ObjectSchema<serializers.TimelineEntriesGetResponse.Raw, DevrevApi.TimelineEntriesGetResponse>;
export declare namespace TimelineEntriesGetResponse {
    interface Raw {
        timeline_entry: serializers.TimelineEntry.Raw;
    }
}
