/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntriesCreateRequestType: core.serialization.Schema<serializers.TimelineEntriesCreateRequestType.Raw, DevrevApi.TimelineEntriesCreateRequestType>;
export declare namespace TimelineEntriesCreateRequestType {
    type Raw = "timeline_comment";
}
