/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineComment: core.serialization.ObjectSchema<serializers.TimelineComment.Raw, DevrevApi.TimelineComment>;
export declare namespace TimelineComment {
    interface Raw extends serializers.TimelineEntryBase.Raw {
        artifacts?: serializers.ArtifactSummary.Raw[] | null;
        body?: string | null;
        body_type?: serializers.TimelineCommentBodyType.Raw | null;
        snap_kit_body?: serializers.TimelineSnapKitBody.Raw | null;
        snap_widget_body?: serializers.SnapWidget.Raw[] | null;
    }
}
