/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntryType: core.serialization.Schema<serializers.TimelineEntryType.Raw, DevrevApi.TimelineEntryType>;
export declare namespace TimelineEntryType {
    type Raw = "timeline_comment";
}
