/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const TimelineEntriesUpdateRequestTimelineComment: core.serialization.ObjectSchema<serializers.TimelineEntriesUpdateRequestTimelineComment.Raw, DevrevApi.TimelineEntriesUpdateRequestTimelineComment>;
export declare namespace TimelineEntriesUpdateRequestTimelineComment {
    interface Raw {
        artifacts?: serializers.TimelineEntriesUpdateRequestTimelineCommentArtifacts.Raw | null;
        body?: string | null;
        body_type?: serializers.TimelineCommentBodyType.Raw | null;
        snap_kit_body?: serializers.TimelineSnapKitBody.Raw | null;
    }
}
