/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const UserType: core.serialization.Schema<serializers.UserType.Raw, DevrevApi.UserType>;
export declare namespace UserType {
    type Raw = "dev_user" | "rev_user" | "sys_user";
}
