/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const UserState: core.serialization.Schema<serializers.UserState.Raw, DevrevApi.UserState>;
export declare namespace UserState {
    type Raw = "active" | "deactivated" | "deleted" | "locked" | "shadow" | "unassigned";
}
