/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WebhooksCreateResponse: core.serialization.ObjectSchema<serializers.WebhooksCreateResponse.Raw, DevrevApi.WebhooksCreateResponse>;
export declare namespace WebhooksCreateResponse {
    interface Raw {
        webhook: serializers.Webhook.Raw;
    }
}
