/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WebhookEventRequest: core.serialization.ObjectSchema<serializers.WebhookEventRequest.Raw, DevrevApi.WebhookEventRequest>;
export declare namespace WebhookEventRequest {
    interface Raw {
        account_created?: serializers.EventAccountCreated.Raw | null;
        account_deleted?: serializers.EventAccountDeleted.Raw | null;
        account_updated?: serializers.EventAccountUpdated.Raw | null;
        conversation_created?: serializers.EventConversationCreated.Raw | null;
        conversation_deleted?: serializers.EventConversationDeleted.Raw | null;
        conversation_updated?: serializers.EventConversationUpdated.Raw | null;
        dev_user_created?: serializers.EventDevUserCreated.Raw | null;
        dev_user_deleted?: serializers.EventDevUserDeleted.Raw | null;
        dev_user_updated?: serializers.EventDevUserUpdated.Raw | null;
        id: string;
        part_created?: serializers.EventPartCreated.Raw | null;
        part_deleted?: serializers.EventPartDeleted.Raw | null;
        part_updated?: serializers.EventPartUpdated.Raw | null;
        rev_org_created?: serializers.EventRevOrgCreated.Raw | null;
        rev_org_deleted?: serializers.EventRevOrgDeleted.Raw | null;
        rev_org_updated?: serializers.EventRevOrgUpdated.Raw | null;
        rev_user_created?: serializers.EventRevUserCreated.Raw | null;
        rev_user_deleted?: serializers.EventRevUserDeleted.Raw | null;
        rev_user_updated?: serializers.EventRevUserUpdated.Raw | null;
        sla_tracker_created?: serializers.EventSlaTrackerCreated.Raw | null;
        sla_tracker_deleted?: serializers.EventSlaTrackerDeleted.Raw | null;
        sla_tracker_updated?: serializers.EventSlaTrackerUpdated.Raw | null;
        survey_response_created?: serializers.EventSurveyResponseCreated.Raw | null;
        survey_response_deleted?: serializers.EventSurveyResponseDeleted.Raw | null;
        survey_response_updated?: serializers.EventSurveyResponseUpdated.Raw | null;
        tag_created?: serializers.EventTagCreated.Raw | null;
        tag_deleted?: serializers.EventTagDeleted.Raw | null;
        tag_updated?: serializers.EventTagUpdated.Raw | null;
        timeline_entry_created?: serializers.EventTimelineEntryCreated.Raw | null;
        timeline_entry_deleted?: serializers.EventTimelineEntryDeleted.Raw | null;
        timeline_entry_updated?: serializers.EventTimelineEntryUpdated.Raw | null;
        timestamp?: string | null;
        type?: serializers.WebhookEventType.Raw | null;
        verify?: serializers.WebhookEventVerify.Raw | null;
        webhook_created?: serializers.EventWebhookCreated.Raw | null;
        webhook_deleted?: serializers.EventWebhookDeleted.Raw | null;
        webhook_id: string;
        webhook_updated?: serializers.EventWebhookUpdated.Raw | null;
        work_created?: serializers.EventWorkCreated.Raw | null;
        work_deleted?: serializers.EventWorkDeleted.Raw | null;
        work_updated?: serializers.EventWorkUpdated.Raw | null;
    }
}
