"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookEventRequest = void 0;
const core = __importStar(require("../../core"));
exports.WebhookEventRequest = core.serialization.object({
    accountCreated: core.serialization.property("account_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventAccountCreated; })).optional()),
    accountDeleted: core.serialization.property("account_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventAccountDeleted; })).optional()),
    accountUpdated: core.serialization.property("account_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventAccountUpdated; })).optional()),
    conversationCreated: core.serialization.property("conversation_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventConversationCreated; })).optional()),
    conversationDeleted: core.serialization.property("conversation_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventConversationDeleted; })).optional()),
    conversationUpdated: core.serialization.property("conversation_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventConversationUpdated; })).optional()),
    devUserCreated: core.serialization.property("dev_user_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventDevUserCreated; })).optional()),
    devUserDeleted: core.serialization.property("dev_user_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventDevUserDeleted; })).optional()),
    devUserUpdated: core.serialization.property("dev_user_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventDevUserUpdated; })).optional()),
    id: core.serialization.string(),
    partCreated: core.serialization.property("part_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventPartCreated; })).optional()),
    partDeleted: core.serialization.property("part_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventPartDeleted; })).optional()),
    partUpdated: core.serialization.property("part_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventPartUpdated; })).optional()),
    revOrgCreated: core.serialization.property("rev_org_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventRevOrgCreated; })).optional()),
    revOrgDeleted: core.serialization.property("rev_org_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventRevOrgDeleted; })).optional()),
    revOrgUpdated: core.serialization.property("rev_org_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventRevOrgUpdated; })).optional()),
    revUserCreated: core.serialization.property("rev_user_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventRevUserCreated; })).optional()),
    revUserDeleted: core.serialization.property("rev_user_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventRevUserDeleted; })).optional()),
    revUserUpdated: core.serialization.property("rev_user_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventRevUserUpdated; })).optional()),
    slaTrackerCreated: core.serialization.property("sla_tracker_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventSlaTrackerCreated; })).optional()),
    slaTrackerDeleted: core.serialization.property("sla_tracker_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventSlaTrackerDeleted; })).optional()),
    slaTrackerUpdated: core.serialization.property("sla_tracker_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventSlaTrackerUpdated; })).optional()),
    surveyResponseCreated: core.serialization.property("survey_response_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventSurveyResponseCreated; })).optional()),
    surveyResponseDeleted: core.serialization.property("survey_response_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventSurveyResponseDeleted; })).optional()),
    surveyResponseUpdated: core.serialization.property("survey_response_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventSurveyResponseUpdated; })).optional()),
    tagCreated: core.serialization.property("tag_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventTagCreated; })).optional()),
    tagDeleted: core.serialization.property("tag_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventTagDeleted; })).optional()),
    tagUpdated: core.serialization.property("tag_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventTagUpdated; })).optional()),
    timelineEntryCreated: core.serialization.property("timeline_entry_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventTimelineEntryCreated; })).optional()),
    timelineEntryDeleted: core.serialization.property("timeline_entry_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventTimelineEntryDeleted; })).optional()),
    timelineEntryUpdated: core.serialization.property("timeline_entry_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventTimelineEntryUpdated; })).optional()),
    timestamp: core.serialization.date().optional(),
    type: core.serialization.lazy(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).WebhookEventType; })).optional(),
    verify: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).WebhookEventVerify; })).optional(),
    webhookCreated: core.serialization.property("webhook_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventWebhookCreated; })).optional()),
    webhookDeleted: core.serialization.property("webhook_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventWebhookDeleted; })).optional()),
    webhookId: core.serialization.property("webhook_id", core.serialization.string()),
    webhookUpdated: core.serialization.property("webhook_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventWebhookUpdated; })).optional()),
    workCreated: core.serialization.property("work_created", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventWorkCreated; })).optional()),
    workDeleted: core.serialization.property("work_deleted", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventWorkDeleted; })).optional()),
    workUpdated: core.serialization.property("work_updated", core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).EventWorkUpdated; })).optional()),
});
