/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WebhooksListRequest: core.serialization.Schema<serializers.WebhooksListRequest.Raw, DevrevApi.WebhooksListRequest>;
export declare namespace WebhooksListRequest {
    type Raw = Record<string, unknown>;
}
