/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WebhooksListResponse: core.serialization.ObjectSchema<serializers.WebhooksListResponse.Raw, DevrevApi.WebhooksListResponse>;
export declare namespace WebhooksListResponse {
    interface Raw {
        webhooks: serializers.Webhook.Raw[];
    }
}
