/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorksUpdateRequestOwnedBy: core.serialization.ObjectSchema<serializers.WorksUpdateRequestOwnedBy.Raw, DevrevApi.WorksUpdateRequestOwnedBy>;
export declare namespace WorksUpdateRequestOwnedBy {
    interface Raw {
        set?: string[] | null;
    }
}
