/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorksDeleteResponse: core.serialization.Schema<serializers.WorksDeleteResponse.Raw, DevrevApi.WorksDeleteResponse>;
export declare namespace WorksDeleteResponse {
    type Raw = Record<string, unknown>;
}
