/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorksUpdateRequestArtifacts: core.serialization.ObjectSchema<serializers.WorksUpdateRequestArtifacts.Raw, DevrevApi.WorksUpdateRequestArtifacts>;
export declare namespace WorksUpdateRequestArtifacts {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
        set?: string[] | null;
    }
}
