/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const Work: core.serialization.Schema<serializers.Work.Raw, DevrevApi.Work>;
export declare namespace Work {
    type Raw = Work.Issue | Work.Ticket;
    interface Issue extends serializers.Issue.Raw {
        type: "issue";
    }
    interface Ticket extends serializers.Ticket.Raw {
        type: "ticket";
    }
}
