/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorksUpdateRequestTicket: core.serialization.ObjectSchema<serializers.WorksUpdateRequestTicket.Raw, DevrevApi.WorksUpdateRequestTicket>;
export declare namespace WorksUpdateRequestTicket {
    interface Raw {
        channels?: serializers.WorksUpdateRequestTicketChannels.Raw | null;
        group?: string | null;
        is_spam?: boolean | null;
        needs_response?: boolean | null;
        rev_org?: string | null;
        severity?: serializers.TicketSeverity.Raw | null;
    }
}
