/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorkType: core.serialization.Schema<serializers.WorkType.Raw, DevrevApi.WorkType>;
export declare namespace WorkType {
    type Raw = "issue" | "ticket";
}
