/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../core";
import * as serializers from "..";
import * as DevrevApi from "../../api";
export declare const WorksCreateRequest: core.serialization.Schema<serializers.WorksCreateRequest.Raw, DevrevApi.WorksCreateRequest>;
export declare namespace WorksCreateRequest {
    type Raw = WorksCreateRequest.Issue | WorksCreateRequest.Ticket;
    interface Issue extends _Base, serializers.WorksCreateRequestIssue.Raw {
        type: "issue";
    }
    interface Ticket extends _Base, serializers.WorksCreateRequestTicket.Raw {
        type: "ticket";
    }
    interface _Base {
        applies_to_part: string;
        artifacts?: string[] | null;
        body?: string | null;
        owned_by: string[];
        reported_by?: string[] | null;
        stage?: serializers.StageInit.Raw | null;
        tags?: serializers.SetTagWithValue.Raw[] | null;
        target_close_date?: string | null;
        title: string;
    }
}
