/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorkBase: core.serialization.ObjectSchema<serializers.WorkBase.Raw, DevrevApi.WorkBase>;
export declare namespace WorkBase {
    interface Raw extends serializers.AtomBase.Raw {
        applies_to_part?: serializers.PartSummary.Raw | null;
        artifacts?: serializers.ArtifactSummary.Raw[] | null;
        body?: string | null;
        owned_by: serializers.UserSummary.Raw[];
        reported_by?: serializers.UserSummary.Raw[] | null;
        stage?: serializers.LegacyStage.Raw | null;
        tags?: serializers.TagWithValue.Raw[] | null;
        target_close_date?: string | null;
        title: string;
    }
}
