/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorksUpdateRequestTicketChannels: core.serialization.ObjectSchema<serializers.WorksUpdateRequestTicketChannels.Raw, DevrevApi.WorksUpdateRequestTicketChannels>;
export declare namespace WorksUpdateRequestTicketChannels {
    interface Raw {
        set?: serializers.TicketChannels.Raw[] | null;
    }
}
