/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorksCreateResponse: core.serialization.ObjectSchema<serializers.WorksCreateResponse.Raw, DevrevApi.WorksCreateResponse>;
export declare namespace WorksCreateResponse {
    interface Raw {
        work: serializers.Work.Raw;
    }
}
