/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorksUpdateRequestTags: core.serialization.ObjectSchema<serializers.WorksUpdateRequestTags.Raw, DevrevApi.WorksUpdateRequestTags>;
export declare namespace WorksUpdateRequestTags {
    interface Raw {
        set?: serializers.SetTagWithValue.Raw[] | null;
    }
}
