/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as DevrevApi from "../../api";
import * as core from "../../core";
export declare const WorksUpdateRequestIssue: core.serialization.ObjectSchema<serializers.WorksUpdateRequestIssue.Raw, DevrevApi.WorksUpdateRequestIssue>;
export declare namespace WorksUpdateRequestIssue {
    interface Raw {
        developed_with?: serializers.WorksUpdateRequestIssueDevelopedWith.Raw | null;
        priority?: serializers.IssuePriority.Raw | null;
        priority_v2?: number | null;
        sprint?: string | null;
        target_start_date?: string | null;
    }
}
