"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DevrevApiTimeoutError = void 0;
class DevrevApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, DevrevApiTimeoutError.prototype);
    }
}
exports.DevrevApiTimeoutError = DevrevApiTimeoutError;
