/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The response to exporting a collection of accounts.
 */
export interface AccountsExportResponse {
    /** The exported accounts. */
    accounts: DevrevApi.Account[];
}
