/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface Account extends DevrevApi.OrgBase {
    /** Description of the corresponding Account. */
    description?: string;
    /** Company's domain names. Example - 'devrev.ai'. */
    domains?: string[];
    /**
     * External refs are unique identifiers from your customer system of
     * records, stored as a list.
     */
    externalRefs: string[];
    /** List of Dev user IDs owning this Account. */
    ownedBy: DevrevApi.UserSummary[];
    /** The Tier of the corresponding Account. */
    tier?: string;
}
