/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * Updated account object.
 */
export interface AccountsUpdateResponse {
    account: DevrevApi.Account;
}
