/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The returned account.
 */
export interface AccountsGetResponse {
    account: DevrevApi.Account;
}
