/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * Metric with corresponding target values.
 */
export interface ArchetypeMetricTarget {
    /**
     * If true, the schedule attached to this metric is out of schedule at
     * the time of the query.
     */
    isOutOfSchedule?: boolean;
    metricDefinition: DevrevApi.MetricDefinitionSummary;
    orgSchedule?: DevrevApi.OrgScheduleSummary;
    /** Time in minutes that remains on a paused metric. */
    remainingTime?: number;
    /** Time at which the metric would breach SLA if no action taken. */
    targetTime?: Date;
    /**
     * Time at which the metric would reach the SLA warning limit if no
     * action taken.
     */
    warningTargetTime?: Date;
}
