/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The version of the artifact.
 */
export interface ArtifactVersion {
    modifiedBy?: DevrevApi.UserSummary;
    /** The timestamp at which the version was created. */
    timestamp: Date;
    /** The version of the artifact. */
    version: string;
}
