/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The response to list artifacts attached to an object.
 */
export interface ArtifactsListResponse {
    /** The artifact's information. */
    artifacts: DevrevApi.Artifact[];
}
