/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface AtomBase {
    createdBy?: DevrevApi.UserSummary;
    /** Timestamp when the object was created. */
    createdDate?: Date;
    /** Human-readable object ID unique to the Dev organization. */
    displayId?: string;
    /** Globally unique object ID. */
    id: string;
    modifiedBy?: DevrevApi.UserSummary;
    /** Timestamp when the object was last modified. */
    modifiedDate?: Date;
}
