/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The response to get the token metadata.
 */
export interface AuthTokensGetResponse {
    token: DevrevApi.AuthToken;
}
