/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The response to list the token metadata.
 */
export interface AuthTokensListResponse {
    /** The list of token metadata. */
    tokens: DevrevApi.AuthToken[];
}
