"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthTokenSubjectTokenType = void 0;
exports.AuthTokenSubjectTokenType = {
    UrnDevrevParamsOauthTokenTypeJwtAuth0: "urn:devrev:params:oauth:token-type:jwt:auth0",
    UrnDevrevParamsOauthTokenTypeJwtDev: "urn:devrev:params:oauth:token-type:jwt:dev",
    UrnDevrevParamsOauthTokenTypeRat: "urn:devrev:params:oauth:token-type:rat",
    UrnDevrevParamsOauthTokenTypeRevinfo: "urn:devrev:params:oauth:token-type:revinfo",
    UrnDevrevParamsOauthTokenTypeSession: "urn:devrev:params:oauth:token-type:session",
    UrnDevrevParamsOauthTokenTypeSysu: "urn:devrev:params:oauth:token-type:sysu",
    UrnDevrevParamsOauthTokenTypeUserinfo: "urn:devrev:params:oauth:token-type:userinfo",
    UrnDevrevParamsOauthTokenTypeUserinfoProfile: "urn:devrev:params:oauth:token-type:userinfo:profile",
    UrnIetfParamsOauthTokenTypeJwt: "urn:ietf:params:oauth:token-type:jwt",
};
