"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthConnectionType = void 0;
exports.AuthConnectionType = {
    GoogleApps: "google_apps",
    Oidc: "oidc",
    Samlp: "samlp",
    Social: "social",
    Waad: "waad",
};
