"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthTokenStatus = void 0;
exports.AuthTokenStatus = {
    Active: "active",
    Expired: "expired",
    Revoked: "revoked",
};
