/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the requested token.
 */
export declare type AuthTokenRequestedTokenType = "urn:devrev:params:oauth:token-type:aat" | "urn:devrev:params:oauth:token-type:aat:act-as" | "urn:devrev:params:oauth:token-type:aat:public" | "urn:devrev:params:oauth:token-type:dev" | "urn:devrev:params:oauth:token-type:dev:connect" | "urn:devrev:params:oauth:token-type:gat" | "urn:devrev:params:oauth:token-type:pat" | "urn:devrev:params:oauth:token-type:pat:act-as" | "urn:devrev:params:oauth:token-type:rat" | "urn:devrev:params:oauth:token-type:rev" | "urn:devrev:params:oauth:token-type:session" | "urn:devrev:params:oauth:token-type:session:dev0" | "urn:devrev:params:oauth:token-type:session:onetime" | "urn:devrev:params:oauth:token-type:session:rev:act-as" | "urn:devrev:params:oauth:token-type:super" | "urn:devrev:params:oauth:token-type:sys" | "urn:ietf:params:oauth:token-type:jwt";
export declare const AuthTokenRequestedTokenType: {
    readonly UrnDevrevParamsOauthTokenTypeAat: "urn:devrev:params:oauth:token-type:aat";
    readonly UrnDevrevParamsOauthTokenTypeAatActAs: "urn:devrev:params:oauth:token-type:aat:act-as";
    readonly UrnDevrevParamsOauthTokenTypeAatPublic: "urn:devrev:params:oauth:token-type:aat:public";
    readonly UrnDevrevParamsOauthTokenTypeDev: "urn:devrev:params:oauth:token-type:dev";
    readonly UrnDevrevParamsOauthTokenTypeDevConnect: "urn:devrev:params:oauth:token-type:dev:connect";
    readonly UrnDevrevParamsOauthTokenTypeGat: "urn:devrev:params:oauth:token-type:gat";
    readonly UrnDevrevParamsOauthTokenTypePat: "urn:devrev:params:oauth:token-type:pat";
    readonly UrnDevrevParamsOauthTokenTypePatActAs: "urn:devrev:params:oauth:token-type:pat:act-as";
    readonly UrnDevrevParamsOauthTokenTypeRat: "urn:devrev:params:oauth:token-type:rat";
    readonly UrnDevrevParamsOauthTokenTypeRev: "urn:devrev:params:oauth:token-type:rev";
    readonly UrnDevrevParamsOauthTokenTypeSession: "urn:devrev:params:oauth:token-type:session";
    readonly UrnDevrevParamsOauthTokenTypeSessionDev0: "urn:devrev:params:oauth:token-type:session:dev0";
    readonly UrnDevrevParamsOauthTokenTypeSessionOnetime: "urn:devrev:params:oauth:token-type:session:onetime";
    readonly UrnDevrevParamsOauthTokenTypeSessionRevActAs: "urn:devrev:params:oauth:token-type:session:rev:act-as";
    readonly UrnDevrevParamsOauthTokenTypeSuper: "urn:devrev:params:oauth:token-type:super";
    readonly UrnDevrevParamsOauthTokenTypeSys: "urn:devrev:params:oauth:token-type:sys";
    readonly UrnIetfParamsOauthTokenTypeJwt: "urn:ietf:params:oauth:token-type:jwt";
};
