/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type AuthConnectionToggle = "disable" | "enable";
export declare const AuthConnectionToggle: {
    readonly Disable: "disable";
    readonly Enable: "enable";
};
