"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AuthTokenGrantType = void 0;
exports.AuthTokenGrantType = {
    UrnDevrevParamsOauthGrantTypeTokenIssue: "urn:devrev:params:oauth:grant-type:token-issue",
    UrnIetfParamsOauthGrantTypeTokenExchange: "urn:ietf:params:oauth:grant-type:token-exchange",
};
