/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Specifies the process of obtaining a token.
 */
export declare type AuthTokenGrantType = "urn:devrev:params:oauth:grant-type:token-issue" | "urn:ietf:params:oauth:grant-type:token-exchange";
export declare const AuthTokenGrantType: {
    readonly UrnDevrevParamsOauthGrantTypeTokenIssue: "urn:devrev:params:oauth:grant-type:token-issue";
    readonly UrnIetfParamsOauthGrantTypeTokenExchange: "urn:ietf:params:oauth:grant-type:token-exchange";
};
