/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * Provides ways to specify date ranges on objects.
 */
export declare type DateFilter = DevrevApi.DateFilter.Preset | DevrevApi.DateFilter.Range;
export declare namespace DateFilter {
    interface Preset {
        type: "preset";
        value: DevrevApi.DateTimePreset;
    }
    interface Range extends DevrevApi.DateTimeFilter {
        type: "range";
    }
}
