/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Type of date filter.
 */
export declare type DateFilterType = "preset" | "range";
export declare const DateFilterType: {
    readonly Preset: "preset";
    readonly Range: "range";
};
