/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Specifies the type for the authentication connection. Different types
 * of authentication connections have different configuration parameters
 * that can be updated.
 */
export declare type DevOrgAuthConnectionsUpdateRequestType = "google_apps" | "none" | "oidc" | "samlp" | "waad";
export declare const DevOrgAuthConnectionsUpdateRequestType: {
    readonly GoogleApps: "google_apps";
    readonly None: "none";
    readonly Oidc: "oidc";
    readonly Samlp: "samlp";
    readonly Waad: "waad";
};
