/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * Request to create a new enterprise authentication connection.
 */
export declare type DevOrgAuthConnectionsCreateRequest = DevrevApi.DevOrgAuthConnectionsCreateRequest.GoogleApps | DevrevApi.DevOrgAuthConnectionsCreateRequest.Oidc | DevrevApi.DevOrgAuthConnectionsCreateRequest.Samlp | DevrevApi.DevOrgAuthConnectionsCreateRequest.Waad;
export declare namespace DevOrgAuthConnectionsCreateRequest {
    interface GoogleApps extends DevrevApi.AuthConnectionOptionsGoogleApps, _Base {
        type: "google_apps";
    }
    interface Oidc extends DevrevApi.AuthConnectionOptionsOidc, _Base {
        type: "oidc";
    }
    interface Samlp extends DevrevApi.AuthConnectionOptionsSaml, _Base {
        type: "samlp";
    }
    interface Waad extends DevrevApi.AuthConnectionOptionsAzureAd, _Base {
        type: "waad";
    }
    interface _Base {
        /**
         * Display name of the authentication connection. This name will be
         * visible to all the users when they sign in to this Dev
         * organization. For example, if the display_name is 'abclogin', then
         * it would appear on the login button as 'Log in to abclogin'.
         */
        displayName?: string;
    }
}
