/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * Response object encapsulating the configuration details of an
 * authentication connection.
 */
export interface DevOrgAuthConnectionsGetResponse {
    authConnection: DevrevApi.AuthConnection;
}
