/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A request to get the authenticated user's information.
 */
export declare type DevUsersSelfRequest = Record<string, unknown>;
