"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorBadRequestUnexpectedJsonTypeType = void 0;
exports.ErrorBadRequestUnexpectedJsonTypeType = {
    Array: "array",
    Bool: "bool",
    Null: "null",
    Number: "number",
    Object: "object",
    String: "string",
};
