/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface Issue extends DevrevApi.WorkBase {
    /** Parts associated based on git events. */
    developedWith?: DevrevApi.PartSummary[];
    priority?: DevrevApi.IssuePriority;
    /** Target start date for the object. */
    targetStartDate?: Date;
}
