/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Priority of the work based upon impact and criticality.
 */
export declare type IssuePriority = "p0" | "p1" | "p2" | "p3";
export declare const IssuePriority: {
    readonly P0: "p0";
    readonly P1: "p1";
    readonly P2: "p2";
    readonly P3: "p3";
};
