"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ListMode = void 0;
exports.ListMode = {
    After: "after",
    Before: "before",
};
