/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface OrgBase extends DevrevApi.AtomBase {
    /** Name of the Organization. */
    displayName?: string;
}
