/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface OrgBaseSummary extends DevrevApi.AtomBaseSummary {
    /** Name of the Organization. */
    displayName?: string;
}
