"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrgEnvironment = void 0;
exports.OrgEnvironment = {
    Production: "production",
    Staging: "staging",
    Test: "test",
};
