/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export declare type OrgSummary = DevrevApi.OrgSummary.RevOrg;
export declare namespace OrgSummary {
    interface RevOrg extends DevrevApi.OrgBaseSummary {
        type: "rev_org";
    }
}
