"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrgScheduleStatus = void 0;
exports.OrgScheduleStatus = {
    Archived: "archived",
    Draft: "draft",
    Published: "published",
};
