/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export declare type Part = DevrevApi.Part.Capability | DevrevApi.Part.Enhancement | DevrevApi.Part.Feature | DevrevApi.Part.Product;
export declare namespace Part {
    interface Capability extends DevrevApi.PartBase {
        type: "capability";
    }
    interface Enhancement extends DevrevApi.PartBase {
        type: "enhancement";
    }
    interface Feature extends DevrevApi.PartBase {
        type: "feature";
    }
    interface Product extends DevrevApi.PartBase {
        type: "product";
    }
}
