/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export declare type PartSummary = DevrevApi.PartSummary.Capability | DevrevApi.PartSummary.Enhancement | DevrevApi.PartSummary.Feature | DevrevApi.PartSummary.Product;
export declare namespace PartSummary {
    interface Capability extends DevrevApi.PartBaseSummary {
        type: "capability";
    }
    interface Enhancement extends DevrevApi.PartBaseSummary {
        type: "enhancement";
    }
    interface Feature extends DevrevApi.PartBaseSummary {
        type: "feature";
    }
    interface Product extends DevrevApi.PartBaseSummary {
        type: "product";
    }
}
