/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export declare type PartsUpdateRequest = DevrevApi.PartsUpdateRequest.Capability | DevrevApi.PartsUpdateRequest.Enhancement | DevrevApi.PartsUpdateRequest.Feature | DevrevApi.PartsUpdateRequest.None | DevrevApi.PartsUpdateRequest.Product;
export declare namespace PartsUpdateRequest {
    interface Capability extends _Base {
        type: "capability";
        value: DevrevApi.PartsUpdateRequestCapability;
    }
    interface Enhancement extends DevrevApi.PartsUpdateRequestEnhancement, _Base {
        type: "enhancement";
    }
    interface Feature extends _Base {
        type: "feature";
        value: DevrevApi.PartsUpdateRequestFeature;
    }
    interface None extends _Base {
        type: "none";
        value: DevrevApi.Empty;
    }
    interface Product extends _Base {
        type: "product";
        value: DevrevApi.PartsUpdateRequestProduct;
    }
    interface _Base {
        artifacts?: DevrevApi.PartsUpdateRequestArtifacts;
        /** The updated description of the part. */
        description?: string;
        /** The ID of the part to update. */
        id: string;
        /** The updated name of the part. */
        name?: string;
        ownedBy?: DevrevApi.PartsUpdateRequestOwnedBy;
    }
}
