/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export declare type PartsCreateRequest = DevrevApi.PartsCreateRequest.Capability | DevrevApi.PartsCreateRequest.Enhancement | DevrevApi.PartsCreateRequest.Feature | DevrevApi.PartsCreateRequest.Product;
export declare namespace PartsCreateRequest {
    interface Capability extends DevrevApi.PartsCreateRequestCapability, _Base {
        type: "capability";
    }
    interface Enhancement extends DevrevApi.PartsCreateRequestEnhancement, _Base {
        type: "enhancement";
    }
    interface Feature extends DevrevApi.PartsCreateRequestFeature, _Base {
        type: "feature";
    }
    interface Product extends _Base {
        type: "product";
        value: DevrevApi.PartsCreateRequestProduct;
    }
    interface _Base {
        /** The IDs of the artifacts. */
        artifacts?: string[];
        /** Description of the part. */
        description?: string;
        /** Name of the part. */
        name: string;
        /** The users that own the part. */
        ownedBy: string[];
    }
}
