/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type PartType = "capability" | "enhancement" | "feature" | "product";
export declare const PartType: {
    readonly Capability: "capability";
    readonly Enhancement: "enhancement";
    readonly Feature: "feature";
    readonly Product: "product";
};
