/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface PartBase extends DevrevApi.AtomBase {
    /** The attached artifacts. */
    artifacts?: DevrevApi.ArtifactSummary[];
    /** Description of the part. */
    description?: string;
    /** Name of the part. */
    name: string;
    /** The users that own the part. */
    ownedBy: DevrevApi.UserSummary[];
    /** Tags associated with the object. */
    tags?: DevrevApi.TagWithValue[];
}
