/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * Response object for request to create a new Rev organization.
 */
export interface RevOrgsCreateResponse {
    revOrg: DevrevApi.RevOrg;
}
