/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The filter for SLA summary.
 */
export interface SlaSummaryFilter {
    /** Filters for records with any of the provided SLA stages. */
    stage?: DevrevApi.SlaSummaryStage[];
    targetTime?: DevrevApi.DateFilter;
}
