"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SlaSummaryStage = void 0;
exports.SlaSummaryStage = {
    Breached: "breached",
    Completed: "completed",
    Paused: "paused",
    Running: "running",
    Warning: "warning",
};
