/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The stage of the SLA. This is the metric stage which is closest to
 * breach.
 */
export declare type SlaSummaryStage = "breached" | "completed" | "paused" | "running" | "warning";
export declare const SlaSummaryStage: {
    readonly Breached: "breached";
    readonly Completed: "completed";
    readonly Paused: "paused";
    readonly Running: "running";
    readonly Warning: "warning";
};
