/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface SurveyResponse extends DevrevApi.AtomBase {
    /** The unique ID associated with the dispatched survey. */
    dispatchId?: string;
    /** The ID of the object for which survey is taken. */
    object?: string;
    /** Response for the survey. */
    response?: Record<string, unknown>;
    /** The ID of the survey for which response is taken. */
    survey?: string;
}
