"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SyncMetadataFilterSyncInFilterStatus = void 0;
exports.SyncMetadataFilterSyncInFilterStatus = {
    Failed: "failed",
    Modified: "modified",
    Staged: "staged",
    Succeeded: "succeeded",
};
