/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type SyncMetadataFilterSyncInFilterStatus = "failed" | "modified" | "staged" | "succeeded";
export declare const SyncMetadataFilterSyncInFilterStatus: {
    readonly Failed: "failed";
    readonly Modified: "modified";
    readonly Staged: "staged";
    readonly Succeeded: "succeeded";
};
