/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface SyncMetadataFilter {
    lastSyncIn?: DevrevApi.SyncMetadataFilterSyncInFilter;
    lastSyncOut?: DevrevApi.SyncMetadataFilterSyncOutFilter;
    /** Filters for issues synced from this specific origin system. */
    originSystem?: string[];
}
