/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type SyncMetadataFilterSyncOutFilterStatus = "failed" | "succeeded";
export declare const SyncMetadataFilterSyncOutFilterStatus: {
    readonly Failed: "failed";
    readonly Succeeded: "succeeded";
};
