/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The response to getting a tag's information.
 */
export interface TagsGetResponse {
    tag: DevrevApi.Tag;
}
