/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface TagWithValue {
    tag: DevrevApi.TagSummary;
    /** The value for the object's association with the tag. */
    value?: string;
}
