/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface Ticket extends DevrevApi.WorkBase {
    /** Channels of the ticket. */
    channels?: DevrevApi.TicketChannels[];
    group?: DevrevApi.GroupSummary;
    revOrg?: DevrevApi.OrgSummary;
    severity?: DevrevApi.TicketSeverity;
    slaTracker?: DevrevApi.SlaTrackerSummary;
    /** Source channel of the ticket. */
    sourceChannel?: string;
}
