"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TicketSeverity = void 0;
exports.TicketSeverity = {
    Blocker: "blocker",
    High: "high",
    Low: "low",
    Medium: "medium",
};
