"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TicketChannels = void 0;
exports.TicketChannels = {
    Email: "email",
    Plug: "plug",
    Slack: "slack",
};
