/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of object that the Timeline entry belongs to.
 */
export declare type TimelineEntryObjectType = "capability" | "conversation" | "enhancement" | "feature" | "issue" | "product" | "rev_org" | "rev_user" | "ticket" | "timeline_comment";
export declare const TimelineEntryObjectType: {
    readonly Capability: "capability";
    readonly Conversation: "conversation";
    readonly Enhancement: "enhancement";
    readonly Feature: "feature";
    readonly Issue: "issue";
    readonly Product: "product";
    readonly RevOrg: "rev_org";
    readonly RevUser: "rev_user";
    readonly Ticket: "ticket";
    readonly TimelineComment: "timeline_comment";
};
