/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface TimelineComment extends DevrevApi.TimelineEntryBase {
    /** The artifacts for the comment. */
    artifacts?: DevrevApi.ArtifactSummary[];
    /**
     * The comment's body. If the comment has been deleted, then no body
     * will appear in the response.
     */
    body?: string;
    bodyType?: DevrevApi.TimelineCommentBodyType;
    snapKitBody?: DevrevApi.TimelineSnapKitBody;
    /** The snap widget body of the comment. */
    snapWidgetBody?: DevrevApi.SnapWidget[];
}
