/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The response to deleting a timeline entry from an object.
 */
export declare type TimelineEntriesDeleteResponse = Record<string, unknown>;
