"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TimelineCommentBodyType = void 0;
exports.TimelineCommentBodyType = {
    SnapKit: "snap_kit",
    SnapWidget: "snap_widget",
    Text: "text",
};
