/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The type of the body to use for the comment.
 */
export declare type TimelineCommentBodyType = "snap_kit" | "snap_widget" | "text";
export declare const TimelineCommentBodyType: {
    readonly SnapKit: "snap_kit";
    readonly SnapWidget: "snap_widget";
    readonly Text: "text";
};
