/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The request to getting a timeline entry.
 */
export interface TimelineEntriesGetResponse {
    timelineEntry: DevrevApi.TimelineEntry;
}
