/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface UserBase extends DevrevApi.AtomBase {
    /** The user's display name. The name is non-unique and mutable. */
    displayName?: string;
    displayPicture?: DevrevApi.ArtifactSummary;
    /** Email address of the user. */
    email?: string;
    /** Full name of the user. */
    fullName?: string;
    /** Phone numbers of the user. */
    phoneNumbers?: string[];
    state?: DevrevApi.UserState;
}
