/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * State of the user.
 */
export declare type UserState = "active" | "deactivated" | "deleted" | "locked" | "shadow" | "unassigned";
export declare const UserState: {
    readonly Active: "active";
    readonly Deactivated: "deactivated";
    readonly Deleted: "deleted";
    readonly Locked: "locked";
    readonly Shadow: "shadow";
    readonly Unassigned: "unassigned";
};
