/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type UserType = "dev_user" | "rev_user" | "sys_user";
export declare const UserType: {
    readonly DevUser: "dev_user";
    readonly RevUser: "rev_user";
    readonly SysUser: "sys_user";
};
