/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export declare type UserSummary = DevrevApi.UserSummary.DevUser | DevrevApi.UserSummary.RevUser | DevrevApi.UserSummary.SysUser;
export declare namespace UserSummary {
    interface DevUser extends DevrevApi.UserBaseSummary {
        type: "dev_user";
    }
    interface RevUser extends DevrevApi.RevUserSummary {
        type: "rev_user";
    }
    interface SysUser extends DevrevApi.UserBaseSummary {
        type: "sys_user";
    }
}
