"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserState = void 0;
exports.UserState = {
    Active: "active",
    Deactivated: "deactivated",
    Deleted: "deleted",
    Locked: "locked",
    Shadow: "shadow",
    Unassigned: "unassigned",
};
