/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The event types that the webhook will receive.
 */
export declare type WebhookEventType = "account_created" | "account_deleted" | "account_updated" | "conversation_created" | "conversation_deleted" | "conversation_updated" | "dev_user_created" | "dev_user_deleted" | "dev_user_updated" | "part_created" | "part_deleted" | "part_updated" | "rev_org_created" | "rev_org_deleted" | "rev_org_updated" | "rev_user_created" | "rev_user_deleted" | "rev_user_updated" | "sla_tracker_created" | "sla_tracker_deleted" | "sla_tracker_updated" | "tag_created" | "tag_deleted" | "tag_updated" | "timeline_entry_created" | "timeline_entry_deleted" | "timeline_entry_updated" | "verify" | "webhook_created" | "webhook_deleted" | "webhook_updated" | "work_created" | "work_deleted" | "work_updated";
export declare const WebhookEventType: {
    readonly AccountCreated: "account_created";
    readonly AccountDeleted: "account_deleted";
    readonly AccountUpdated: "account_updated";
    readonly ConversationCreated: "conversation_created";
    readonly ConversationDeleted: "conversation_deleted";
    readonly ConversationUpdated: "conversation_updated";
    readonly DevUserCreated: "dev_user_created";
    readonly DevUserDeleted: "dev_user_deleted";
    readonly DevUserUpdated: "dev_user_updated";
    readonly PartCreated: "part_created";
    readonly PartDeleted: "part_deleted";
    readonly PartUpdated: "part_updated";
    readonly RevOrgCreated: "rev_org_created";
    readonly RevOrgDeleted: "rev_org_deleted";
    readonly RevOrgUpdated: "rev_org_updated";
    readonly RevUserCreated: "rev_user_created";
    readonly RevUserDeleted: "rev_user_deleted";
    readonly RevUserUpdated: "rev_user_updated";
    readonly SlaTrackerCreated: "sla_tracker_created";
    readonly SlaTrackerDeleted: "sla_tracker_deleted";
    readonly SlaTrackerUpdated: "sla_tracker_updated";
    readonly TagCreated: "tag_created";
    readonly TagDeleted: "tag_deleted";
    readonly TagUpdated: "tag_updated";
    readonly TimelineEntryCreated: "timeline_entry_created";
    readonly TimelineEntryDeleted: "timeline_entry_deleted";
    readonly TimelineEntryUpdated: "timeline_entry_updated";
    readonly Verify: "verify";
    readonly WebhookCreated: "webhook_created";
    readonly WebhookDeleted: "webhook_deleted";
    readonly WebhookUpdated: "webhook_updated";
    readonly WorkCreated: "work_created";
    readonly WorkDeleted: "work_deleted";
    readonly WorkUpdated: "work_updated";
};
