/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * The action to update the webhook's status.
 */
export declare type WebhooksUpdateAction = "activate" | "deactivate";
export declare const WebhooksUpdateAction: {
    readonly Activate: "activate";
    readonly Deactivate: "deactivate";
};
