"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhooksUpdateAction = void 0;
exports.WebhooksUpdateAction = {
    Activate: "activate",
    Deactivate: "deactivate",
};
