/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The response to listing the webhooks.
 */
export interface WebhooksListResponse {
    /** The list of webhooks. */
    webhooks: DevrevApi.Webhook[];
}
