"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebhookEventType = void 0;
exports.WebhookEventType = {
    AccountCreated: "account_created",
    AccountDeleted: "account_deleted",
    AccountUpdated: "account_updated",
    ConversationCreated: "conversation_created",
    ConversationDeleted: "conversation_deleted",
    ConversationUpdated: "conversation_updated",
    DevUserCreated: "dev_user_created",
    DevUserDeleted: "dev_user_deleted",
    DevUserUpdated: "dev_user_updated",
    PartCreated: "part_created",
    PartDeleted: "part_deleted",
    PartUpdated: "part_updated",
    RevOrgCreated: "rev_org_created",
    RevOrgDeleted: "rev_org_deleted",
    RevOrgUpdated: "rev_org_updated",
    RevUserCreated: "rev_user_created",
    RevUserDeleted: "rev_user_deleted",
    RevUserUpdated: "rev_user_updated",
    SlaTrackerCreated: "sla_tracker_created",
    SlaTrackerDeleted: "sla_tracker_deleted",
    SlaTrackerUpdated: "sla_tracker_updated",
    TagCreated: "tag_created",
    TagDeleted: "tag_deleted",
    TagUpdated: "tag_updated",
    TimelineEntryCreated: "timeline_entry_created",
    TimelineEntryDeleted: "timeline_entry_deleted",
    TimelineEntryUpdated: "timeline_entry_updated",
    Verify: "verify",
    WebhookCreated: "webhook_created",
    WebhookDeleted: "webhook_deleted",
    WebhookUpdated: "webhook_updated",
    WorkCreated: "work_created",
    WorkDeleted: "work_deleted",
    WorkUpdated: "work_updated",
};
