/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The response to getting the information for the webhook.
 */
export interface WebhooksGetResponse {
    webhook: DevrevApi.Webhook;
}
