/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface Webhook extends DevrevApi.AtomBase {
    /** The event types that the webhook will receive. */
    eventTypes?: DevrevApi.WebhookEventType[];
    /** The secret to use for verifying webhook events. */
    secret: string;
    status: DevrevApi.WebhookStatus;
    /** The URL of the webhook endpoint. */
    url: string;
}
