/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
/**
 * The response to creating a new webhook.
 */
export interface WebhooksCreateResponse {
    webhook: DevrevApi.Webhook;
}
