/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export declare type Work = DevrevApi.Work.Issue | DevrevApi.Work.Ticket;
export declare namespace Work {
    interface Issue extends DevrevApi.Issue {
        type: "issue";
    }
    interface Ticket extends DevrevApi.Ticket {
        type: "ticket";
    }
}
