"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkType = void 0;
exports.WorkType = {
    Issue: "issue",
    Ticket: "ticket",
};
