/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface WorkBase extends DevrevApi.AtomBase {
    appliesToPart?: DevrevApi.PartSummary;
    /** The artifacts attached to the work item. */
    artifacts?: DevrevApi.ArtifactSummary[];
    /** Body of the work object. */
    body?: string;
    /** The users that own the work. */
    ownedBy: DevrevApi.UserSummary[];
    /** Users that reported the work. */
    reportedBy?: DevrevApi.UserSummary[];
    stage?: DevrevApi.LegacyStage;
    /** Tags associated with the object. */
    tags?: DevrevApi.TagWithValue[];
    /** Timestamp when the work is expected to be complete. */
    targetCloseDate?: Date;
    /** Title of the work object. */
    title: string;
}
