/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface WorksUpdateRequestIssue {
    developedWith?: DevrevApi.WorksUpdateRequestIssueDevelopedWith;
    priority?: DevrevApi.IssuePriority;
    /** Priority enum id of the work based upon impact and criticality. */
    priorityV2?: number;
    /** Updates the sprint that the issue belongs to. */
    sprint?: string;
    /** Updates the timestamp for when the work is expected to start. */
    targetStartDate?: Date;
}
