/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "..";
export interface WorksFilterIssue {
    /** Filters for issues with any of the provided Accounts. */
    accounts?: string[];
    actualStartDate?: DevrevApi.DateFilter;
    /** Filters for issues with any of the provided priorities. */
    priority?: DevrevApi.IssuePriority[];
    /** Filters for issues with any of the provided priority enum ids. */
    priorityV2?: number[];
    /** Filters for issues with any of the provided Rev organizations. */
    revOrgs?: string[];
    targetStartDate?: DevrevApi.DateFilter;
}
