/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare type WorkType = "issue" | "ticket";
export declare const WorkType: {
    readonly Issue: "issue";
    readonly Ticket: "ticket";
};
