/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "../../../..";
/**
 * @example
 *     {}
 */
export interface DevUsersListRequest {
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /** Filters Dev users based on email addresses. */
    email?: string[];
    /** Filters Dev users based on external identity. */
    externalIdentity?: DevrevApi.DevUserExternalIdentityFilter[];
    /**
     * The maximum number of Dev users to return. The default is '50'.
     *
     */
    limit?: number;
    mode?: DevrevApi.ListMode;
    /**
     * Fields to sort the Dev users by and the direction to sort them.
     *
     */
    sortBy?: string[];
    /** Filters Dev users based on state. */
    state?: DevrevApi.UserState[];
}
