/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const RevOrgsUpdateRequest: core.serialization.Schema<serializers.RevOrgsUpdateRequest.Raw, DevrevApi.RevOrgsUpdateRequest>;
export declare namespace RevOrgsUpdateRequest {
    interface Raw {
        description?: string | null;
        display_name?: string | null;
        domain?: string | null;
        environment?: serializers.OrgEnvironment.Raw | null;
        external_ref?: string | null;
        id: string;
        tier?: string | null;
    }
}
