/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const RevOrgsDeleteRequest: core.serialization.Schema<serializers.RevOrgsDeleteRequest.Raw, DevrevApi.RevOrgsDeleteRequest>;
export declare namespace RevOrgsDeleteRequest {
    interface Raw {
        id: string;
    }
}
