/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as DevrevApi from "../../../..";
/**
 * @example
 *     {}
 */
export interface RevOrgsListRequest {
    /** Filters by creator. */
    createdBy?: string[];
    createdDate?: DevrevApi.DateTimeFilter;
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /** Array of display names of Rev orgs to be filtered. */
    displayName?: string[];
    /** List of external refs to filter Rev organizations for. */
    externalRef?: string[];
    /**
     * The maximum number of Rev organizations to be retrieved per page.
     *
     */
    limit?: number;
    mode?: DevrevApi.ListMode;
    modifiedDate?: DevrevApi.DateTimeFilter;
    /**
     * Fields to sort the Rev organizations by and the direction to sort
     * them.
     *
     */
    sortBy?: string[];
}
