on: 
  pull_request:
    paths:
      - fern/apis/public/openapi-public.yaml
      - fern/apis/beta/openapi-beta.yaml
name: generate-changelog
jobs:
  check-logs:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date.outputs.date }}
      should_continue: ${{ steps.check.outputs.should_continue }}
    steps:
      - name: Get current date
        id: date
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          DATE=$(gh pr view ${{ env.PR_NUMBER }} --json createdAt --jq .[] | cut -d 'T' -f 1)
          echo "date=$DATE" >> $GITHUB_OUTPUT
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Check for existing logs
        id: check
        run: |
          if ls fern/apis/*/changelog/${{ steps.date.outputs.date }}.md >/dev/null 2>&1; then
            echo "Log files already exist, stopping workflow"
            echo "should_continue=false" >> $GITHUB_OUTPUT
          else
            echo "No existing log files found, continuing workflow"
            echo "should_continue=true" >> $GITHUB_OUTPUT
          fi

  generate-diff:
    needs: check-logs
    if: needs.check-logs.outputs.should_continue == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository content
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check out HEAD rev
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: head
      - name: Check out BASE rev
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: base   
      - name: Create dir
        run: |
          mkdir -p temp/beta temp/public
      - name: Running public OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/diff@main
        with:
          base: 'base/fern/apis/public/openapi-public.yaml'
          revision: 'head/fern/apis/public/openapi-public.yaml'
          format: text
          output-to-file: 'temp/public/${{ needs.check-logs.outputs.date }}_oasdiff.md'
      - name: Running beta OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/diff@main
        with:
          base: 'base/fern/apis/beta/openapi-beta.yaml'
          revision: 'head/fern/apis/beta/openapi-beta.yaml'  
          format: text
          output-to-file: 'temp/beta/${{ needs.check-logs.outputs.date }}_oasdiff.md'
      - name: Archive changelogs
        uses: actions/upload-artifact@v4
        with:
          name: changelog-${{ needs.check-logs.outputs.date }}
          path: temp/**
      - name: Generate and commit changelog
        env:
          LLM_JWT: ${{ secrets.LLM_JWT }} 
        run: |
          python changelog.py --date ${{ needs.check-logs.outputs.date }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add fern/apis/*/changelog/${{ needs.check-logs.outputs.date }}.md
          git commit -m "generated by Claude"
          git push