on: 
  pull_request:
    paths:
      - fern/apis/public/openapi-public.yaml
      - fern/apis/beta/openapi-beta.yaml

name: generate-changelog
jobs:
  get-diff: 
    runs-on: ubuntu-latest
    steps: 
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Check out HEAD rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: head
    - name: Check out BASE rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base   
    - name: Create dir
      run: |
        mkdir -p temp/beta temp/public
    - name: Running public OpenAPI Spec diff action
      uses: oasdiff/oasdiff-action/diff@main
      with:
        base: 'base/fern/apis/public/openapi-public.yaml'
        revision: 'head/fern/apis/public/openapi-public.yaml'
        format: text
        output-to-file: 'temp/public/${{ steps.date.outputs.date }}_oasdiff.md'
    - name: Running beta OpenAPI Spec diff action
      uses: oasdiff/oasdiff-action/diff@main
      with:
        base: 'base/fern/apis/beta/openapi-beta.yaml'
        revision: 'head/fern/apis/beta/openapi-beta.yaml'  
        format: text
        output-to-file: 'temp/beta/${{ steps.date.outputs.date }}_oasdiff.md'
    - name: Prompt
      run: |
        python changelog.py --date ${{ steps.date.outputs.date }}
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add fern/apis/*/changelog
        git commit -m "generated by Claude"
        git push
    - name: Archive changelogs
      uses: actions/upload-artifact@v4
      with:
        name: changelog-${{ steps.date.outputs.date }}
        path: temp/**
