on: 
  pull_request:
    paths:
      - fern/apis/public/openapi-public.yaml
      - fern/apis/beta/openapi-beta.yaml

name: generate-changelog
jobs:
  get-diff: 
    runs-on: ubuntu-latest
    steps: 
    - name: Get current date
      id: date
      env:
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.number }}
      run: |
        DATE=$(gh pr view --repo https://github.com/devrev/fern-api-docs ${{ env.PR_NUMBER }} --json createdAt --jq .[] | cut -d 'T' -f 1)
        echo "DATE=$DATE" >> $GITHUB_OUTPUT
        echo "Date PR opened is ${{ env.DATE }}"
    - name: Check out repository content
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Check out HEAD rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: head
    - name: Check out BASE rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base   
    - name: Create dir
      run: |
        mkdir -p temp/beta temp/public
    - name: Running public OpenAPI Spec diff action
      uses: oasdiff/oasdiff-action/diff@main
      with:
        base: 'base/fern/apis/public/openapi-public.yaml'
        revision: 'head/fern/apis/public/openapi-public.yaml'
        format: text
        output-to-file: 'temp/public/${{ env.DATE }}_oasdiff.md'
    - name: Running beta OpenAPI Spec diff action
      uses: oasdiff/oasdiff-action/diff@main
      with:
        base: 'base/fern/apis/beta/openapi-beta.yaml'
        revision: 'head/fern/apis/beta/openapi-beta.yaml'  
        format: text
        output-to-file: 'temp/beta/${{ env.DATE }}_oasdiff.md'
    - name: Archive changelogs
      uses: actions/upload-artifact@v4
      with:
        name: changelog-${{ env.DATE }}
        path: temp/**
    - name: Prompt
      env:
          LLM_JWT: ${{ secrets.LLM_JWT }} 
      run: |
        logfiles="fern/apis/*/changelog/${{ env.DATE }}.md"

        if ls $logfiles >/dev/null 2>&1; then
          logfiles=($logfiles)
          echo "${logfiles[@]} already exist."
        else
          python changelog.py --date ${{ env.DATE }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add fern/apis/*/changelog/${{ env.DATE }}.md
          git commit -m "generated by Claude"
          git push
        fi
