name: ci

on: 
  push: 
    branches: 
      - main 

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Download Fern
        run: npm install -g fern-api

      - name: Generate and Publish Docs public
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --version --api public
    
      - name: Generate and Publish Docs beta
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --version --api beta