name: ci

on:
  pull_request:
    branches:
      - main
      
jobs:
  fern-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: '18'
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
          

      - name: Build Navigation
        run: |
          cd custom-implementation
          yarn
          yarn build
          cd ../

      - name: Install Fern
        run:  npm install -g fern-api

      - name: Check Fern API is valid
        run: fern check