on: 
  pull_request:
    paths:
      - fern/apis/public/openapi-public.yaml
      - fern/apis/beta/openapi-beta.yaml

name: generate-changelog
jobs:
  get-diff: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out HEAD rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: head
    - name: Check out BASE rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base   
    - name: Create dir
      run: |
        mkdir changelog
    - name: Run OpenAPI Diff for public (from HEAD rev)
      uses: docker://openapitools/openapi-diff:latest 
      with:
        args: --markdown changelog/public-diff.md --html changelog/public-diff.html --json changelog/public-diff.json base/fern/apis/public/openapi-public.yaml head/fern/apis/public/openapi-public.yaml
    - name: Run OpenAPI Diff for beta (from HEAD rev)
      uses: docker://openapitools/openapi-diff:latest 
      with:
        args: --markdown changelog/beta-diff.md --html changelog/beta-diff.html --json changelog/beta-diff.json base/fern/apis/beta/openapi-beta.yaml head/fern/apis/beta/openapi-beta.yaml
    - name: Archive changelogs
      uses: actions/upload-artifact@v4
      with:
        name: changelog
        path: changelog/**
