on: 
  pull_request:
    paths:
      - fern/apis/public/openapi-public.yaml
      - fern/apis/beta/openapi-beta.yaml

name: generate-changelog
jobs:
  get-diff: 
    runs-on: ubuntu-latest
    steps: 
    - name: Check out HEAD rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: head
    - name: Check out BASE rev
      uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
        path: base   
    - name: Run OpenAPI Diff for public (from HEAD rev)
      uses: docker://openapitools/openapi-diff:latest 
      with:
        args: --markdown beta-diff.md base/fern/apis/public/openapi-public.yaml head/fern/apis/public/openapi-public.yaml
    - name: Run OpenAPI Diff for beta (from HEAD rev)
      uses: docker://openapitools/openapi-diff:latest 
      with:
        args: --json beta-diff.json base/fern/apis/beta/openapi-beta.yaml head/fern/apis/beta/openapi-beta.yaml
