name: ci

on: 
  push: 
    branches: 
      - main 

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4

      - name: Download Fern
        run: npm install -g fern-api   

      - name: Generate and Publish Docs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: fern generate --docs 
