name: PR Review Suggestions

on:
  pull_request:
    types: [opened, synchronize, labeled]
    paths:
      - '**.md'
      - '**.mdx'

jobs:
  suggest:
    if: contains(github.event.pull_request.labels.*.name, 'stylecheck')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run stylecheck on changed files
        env:
          GITHUB_TOKEN: ${{ secrets.STYLECHECK }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          for file in $(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.mdx?$'); do
            python stylecheck.py "$file"
          done