/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AccountsUpdateRequest: core.serialization.Schema<serializers.AccountsUpdateRequest.Raw, DevrevApi.AccountsUpdateRequest>;
export declare namespace AccountsUpdateRequest {
    interface Raw {
        description?: string | null;
        display_name?: string | null;
        domains?: string[] | null;
        external_refs?: string[] | null;
        id: string;
        owned_by?: string[] | null;
        tier?: string | null;
    }
}
