/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AccountsExportRequest: core.serialization.Schema<serializers.AccountsExportRequest.Raw, DevrevApi.AccountsExportRequest>;
export declare namespace AccountsExportRequest {
    interface Raw {
        created_by?: string[] | null;
        created_date?: serializers.DateTimeFilter.Raw | null;
        display_name?: string[] | null;
        external_refs?: string[] | null;
        first?: number | null;
        modified_date?: serializers.DateTimeFilter.Raw | null;
        sort_by?: string[] | null;
        stage?: string[] | null;
    }
}
