/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AccountsCreateRequest: core.serialization.Schema<serializers.AccountsCreateRequest.Raw, DevrevApi.AccountsCreateRequest>;
export declare namespace AccountsCreateRequest {
    interface Raw {
        description?: string | null;
        display_name: string;
        domains?: string[] | null;
        external_refs?: string[] | null;
        owned_by?: string[] | null;
        tier?: string | null;
        websites?: string[] | null;
    }
}
