/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const AccountsGetRequest: core.serialization.Schema<serializers.AccountsGetRequest.Raw, DevrevApi.AccountsGetRequest>;
export declare namespace AccountsGetRequest {
    interface Raw {
        id: string;
    }
}
