/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as DevrevApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const SlaTrackersGetRequest: core.serialization.Schema<serializers.SlaTrackersGetRequest.Raw, DevrevApi.SlaTrackersGetRequest>;
export declare namespace SlaTrackersGetRequest {
    interface Raw {
        id: string;
    }
}
